resolvers:
  - 'SilverStripe\CMS\GraphQL\Resolver'
modelConfig:
  DataObject:
    operations:
      read:
        plugins:
          getByLink:
            after: filter
      readOne:
        plugins:
          getByLink:
            after: filter
