mappings:
  CMSBatchAction_Publish: SilverStripe\CMS\BatchActions\CMSBatchAction_Publish
  CMSBatchAction_Unpublish: SilverStripe\CMS\BatchActions\CMSBatchAction_Unpublish
  CMSBatchAction_Archive: SilverStripe\CMS\BatchActions\CMSBatchAction_Archive
  CMSBatchAction_Restore: SilverStripe\CMS\BatchActions\CMSBatchAction_Restore
  CMSBatchAction_Delete: SilverStripe\CMS\BatchActions\CMSBatchAction_Delete
  CMSMain: SilverStripe\CMS\Controllers\CMSMain
  CMSPageAddController: SilverStripe\CMS\Controllers\CMSPageAddController
  CMSPageEditController: SilverStripe\CMS\Controllers\CMSPageEditController
  CMSPageHistoryController: SilverStripe\CMS\Controllers\CMSPageHistoryController
  CMSPagesController: SilverStripe\CMS\Controllers\CMSPagesController
  CMSPageSettingsController: SilverStripe\CMS\Controllers\CMSPageSettingsController
  CMSSiteTreeFilter: SilverStripe\CMS\Controllers\CMSSiteTreeFilter
  CMSSiteTreeFilter_PublishedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_PublishedPages
  CMSSiteTreeFilter_DeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_DeletedPages
  CMSSiteTreeFilter_ChangedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_ChangedPages
  CMSSiteTreeFilter_StatusRemovedFromDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusRemovedFromDraftPages
  CMSSiteTreeFilter_StatusDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDraftPages
  CMSSiteTreeFilter_StatusDeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDeletedPages
  CMSSiteTreeFilter_Search: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_Search
  ContentController: SilverStripe\CMS\Controllers\ContentController
  ErrorPageControllerExtension: SilverStripe\CMS\Controllers\ErrorPageControllerExtension
  ErrorPageFileExtension: SilverStripe\CMS\Controllers\ErrorPageFileExtension
  LeftAndMainPageIconsExtension: SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
  ModelAsController: SilverStripe\CMS\Controllers\ModelAsController
  OldPageRedirector: SilverStripe\CMS\Controllers\OldPageRedirector
  RootURLController: SilverStripe\CMS\Controllers\RootURLController
  SilverStripeNavigator: SilverStripe\CMS\Controllers\SilverStripeNavigator
  SilverStripeNavigatorItem: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem
  SilverStripeNavigatorItem_CMSLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_CMSLink
  SilverStripeNavigatorItem_StageLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_StageLink
  SilverStripeNavigatorItem_LiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_LiveLink
  SilverStripeNavigatorItem_ArchiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_ArchiveLink
  SiteTreeURLSegmentField: SilverStripe\CMS\Forms\SiteTreeURLSegmentField
  SiteTreeURLSegmentField_Readonly: SilverStripe\CMS\Forms\SiteTreeURLSegmentField_Readonly
  CurrentPageIdentifier: SilverStripe\CMS\Model\CurrentPageIdentifier
  ErrorPage: SilverStripe\CMS\Model\ErrorPage
  ErrorPage_Controller: SilverStripe\CMS\Model\ErrorPage_Controller
  RedirectorPage: SilverStripe\CMS\Model\RedirectorPage
  RedirectorPage_Controller: SilverStripe\CMS\Model\RedirectorPage_Controller
  SiteTree: SilverStripe\CMS\Model\SiteTree
  SiteTreeExtension: SilverStripe\CMS\Model\SiteTreeExtension
  SiteTreeFileExtension: SilverStripe\CMS\Model\SiteTreeFileExtension
  SiteTreeFolderExtension: SilverStripe\CMS\Model\SiteTreeFolderExtension
  SiteTreeLinkTracking: SilverStripe\CMS\Model\SiteTreeLinkTracking
  SiteTreeLinkTracking_Parser: SilverStripe\CMS\Model\SiteTreeLinkTracking_Parser
  VirtualPage: SilverStripe\CMS\Model\VirtualPage
  VirtualPage_Controller: SilverStripe\CMS\Model\VirtualPage_Controller
  BrokenFilesReport: SilverStripe\CMS\Reports\BrokenFilesReport
  SideReport_BrokenFiles: SilverStripe\CMS\Reports\SideReport_BrokenFiles
  BrokenLinksReport: SilverStripe\CMS\Reports\BrokenLinksReport
  SideReport_BrokenLinks: SilverStripe\CMS\Reports\SideReport_BrokenLinks
  BrokenRedirectorPagesReport: SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  SideReport_BrokenRedirectorPages: SilverStripe\CMS\Reports\SideReport_BrokenRedirectorPages
  BrokenVirtualPagesReport: SilverStripe\CMS\Reports\BrokenVirtualPagesReport
  SideReport_BrokenVirtualPages: SilverStripe\CMS\Reports\SideReport_BrokenVirtualPages
  EmptyPagesReport: SilverStripe\CMS\Reports\EmptyPagesReport
  SideReport_EmptyPages: SilverStripe\CMS\Reports\SideReport_EmptyPages
  RecentlyEditedReport: SilverStripe\CMS\Reports\RecentlyEditedReport
  SideReport_RecentlyEdited: SilverStripe\CMS\Reports\SideReport_RecentlyEdited
  ContentControllerSearchExtension: SilverStripe\CMS\Search\ContentControllerSearchExtension
  SearchForm: SilverStripe\CMS\Search\SearchForm
  MigrateSiteTreeLinkingTask: SilverStripe\CMS\Tasks\MigrateSiteTreeLinkingTask
  RemoveOrphanedPagesTask: SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask
  SiteTreeMaintenanceTask: SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask
