// This file was generated by silverstripe/tx-translator from client/lang/src/ar.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ar', {
    "CMS.ALERTCLASSNAME": "سيتم تحديث نوع الصفحة بعد حفظ الصفحة",
    "CMS.AddSubPage": "أضف صفحة جديدة هنا",
    "CMS.Duplicate": "تكرار",
    "CMS.EditPage": "تحرير",
    "CMS.RollbackToVersion": "هل تريد حقاً الرجوع إلى النسخة #%s من هذه الصفحة؟",
    "CMS.ShowAsList": "أعرض التوابع في شكل قائمة",
    "CMS.ThisPageAndSubpages": "هذه الصفحة وصفحات فرعية",
    "CMS.ThisPageOnly": "هذه الصفحة فقط"
});
}