// This file was generated by silverstripe/tx-translator from client/lang/src/bg.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('bg', {
    "CMS.ALERTCLASSNAME": "Типът на страницата ще бъде обновен, след като тя бъде записана",
    "CMS.AddSubPage": "Добави нова страница тук",
    "CMS.ConfirmRestoreFromLive": "Сигурни ли сте, че искате да възстановите чернова, когато страницата е била публикувана за последен път?",
    "CMS.Duplicate": "Дублирай",
    "CMS.EditPage": "Редактирай",
    "CMS.ONLYSELECTTWO": "В момента можете да сравните само две версии.",
    "CMS.Restore": "Сигурни ли сте, че искате да възстановите страницата от архива?",
    "CMS.RestoreToRoot": "Сигурни ли сте, че искате да възстановите страницата от архива?\n\nТази страница ще бъде разположена на най-високо ниво в дървото.",
    "CMS.RollbackToVersion": "Сигурни ли сте, че искате да върнете версия #%s на тази страница?",
    "CMS.ShowAsList": "Покажи подстраниците в листинг",
    "CMS.ThisPageAndSubpages": "Тази страница и подстраниците ѝ",
    "CMS.ThisPageOnly": "Само тази страница",
    "CMS.Unpublish": "Сигурни ли сте, че искате да премахнете страницата от сайта?\n\nТази страница ще остане като чернова.",
    "CMS.UpdateURL": "Обнови URL",
    "CMS.ViewPage": "Преглед"
});
}