// This file was generated by silverstripe/tx-translator from client/lang/src/cs.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('cs', {
    "CMS.ALERTCLASSNAME": "Typ stránky bude aktualizován až stránka bude uložena",
    "CMS.AddSubPage": "Přidat novou stránku sem",
    "CMS.ConfirmRestoreFromLive": "Určitě chcete obnovit koncept do stavz, kdy stránka byla naposled zveřejněna?",
    "CMS.Duplicate": "Duplikovat",
    "CMS.EditPage": "Editovat",
    "CMS.Restore": "Určitě chcete obnovit tyto stránky z archívu?",
    "CMS.RestoreToRoot": "Určitě chcete obnovit tuto stránku z archívu?\n\nProtože nadřazená stránka není k dispozici, bude obnovena do nejvyšší úrovně.",
    "CMS.RollbackToVersion": "Skutečně chcete vrátit zpět na verzi #%s této stránky?",
    "CMS.ShowAsList": "Zobrazit potomky jako seznam",
    "CMS.ThisPageAndSubpages": "Tuto stránku a podstránky",
    "CMS.ThisPageOnly": "Pouze tuto stránku",
    "CMS.Unpublish": "Určitě chcete odstranit stránku ze zveřejněného webu?\n\nTato stránka bude stále k dispozici ve struktuře webu jako koncept.",
    "CMS.UpdateURL": "Aktualizovat URL",
    "CMS.ViewPage": "Zobrazit"
});
}