// This file was generated by silverstripe/tx-translator from client/lang/src/el.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('el', {
    "CMS.AddSubPage": "Προσθήκη νέας σελίδας εδώ",
    "CMS.ThisPageOnly": "Μόνο αυτή η σελίδα"
});
}