// This file was generated by silverstripe/tx-translator from client/lang/src/es_MX.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('es_MX', {
    "CMS.ALERTCLASSNAME": "La página será actualizada una vez que sea guardada",
    "CMS.AddSubPage": "Agregar página aquí",
    "CMS.ConfirmRestoreFromLive": "¿Estás seguro que deseas revertir el borrador a cuando la página fue publicada por última vez?",
    "CMS.Duplicate": "Duplicada",
    "CMS.EditPage": "Editar",
    "CMS.ONLYSELECTTWO": "Solo puedes comparar dos versiones en este momento.",
    "CMS.Restore": "¿Estás seguro que deseas recuperar esta página del archivo?",
    "CMS.RestoreToRoot": "¿Estás seguro que deseas recuperar esta página del archivo?\n\nPorque la página superior no esta disponible, esta sera recuperada como página de primer nivel.",
    "CMS.RollbackToVersion": "¿Seguro que deseas regresar a la versión #%s de esta página?",
    "CMS.ShowAsList": "Mostrar sub páginas como lista",
    "CMS.ThisPageAndSubpages": "Esta página y sus sub páginas",
    "CMS.ThisPageOnly": "Sólo esta página",
    "CMS.Unpublish": "¿Estás seguro que deseas eliminar la página del sitio público?\n\nEsta página aún estará disponible en el árbol del sitio como borrador.",
    "CMS.UpdateURL": "Actualizar URL",
    "CMS.ViewPage": "Ver"
});
}