// This file was generated by silverstripe/tx-translator from client/lang/src/fa_IR.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fa_IR', {
    "CMS.ALERTCLASSNAME": "نوع صفحه پس از ذخیره‌ی آن به‌روزرسانی می‌شود",
    "CMS.AddSubPage": "افزودن صفحه جدید در اینجا",
    "CMS.ConfirmRestoreFromLive": "آیا مطمئن هستید که پیش‌نویس به آخرین انتشار صفحه بازنشانی شود؟",
    "CMS.Duplicate": "دو نسخه کردن",
    "CMS.EditPage": "ویرایش",
    "CMS.Restore": "آیا مطمئن هستید که این صفحه از آرشیو بازنشانی شود؟",
    "CMS.RestoreToRoot": "آیا اطمینان دارید که می‌خواهید این صفحه را از بایگانی بازنشانی نمایید؟\n\nاز آن‌جائی‌که صفحه‌ی والد موجود نیست به بالاترین لول بازنشانی خواهد شد.",
    "CMS.RollbackToVersion": "آیا واقعاً می‌خواهید به نسخه #%s این صفحه بازگردید؟",
    "CMS.ShowAsList": "نمایش فرزندان به صورت لیست",
    "CMS.ThisPageAndSubpages": "این صفحه و صفحات زیرمجموعه",
    "CMS.ThisPageOnly": "فقط این صفحه",
    "CMS.Unpublish": "آیا اطمینان دارید که می‌خواهید صفحه‌تان را از سایت منتشر‌شده حذف نمایید؟\n\nاین صفحه همچنان در نمای‌درختی سایت به عنوان پیش‌نویس در دسترس خواهد بود.",
    "CMS.UpdateURL": "به روز رسانی URL",
    "CMS.ViewPage": "نمایش"
});
}