// This file was generated by silverstripe/tx-translator from client/lang/src/fi_FI.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi_FI', {
    "CMS.ALERTCLASSNAME": "Sivutyyppi päivitetään sivun tallennuksen jälkeen",
    "CMS.AddSubPage": "Lisää uusi sivu tähän",
    "CMS.ConfirmRestoreFromLive": "Haluatko varmasti palata luonnoksen viimeisimpään julkaistuun versioon?",
    "CMS.Duplicate": "Monista",
    "CMS.EditPage": "Muokkaa",
    "CMS.Restore": "Haluatko varmasti palauttaa sivun arkistosta?",
    "CMS.RestoreToRoot": "Haluatko varmasti palauttaa tämän sivun arkistosta?\n\nKoska isäntäsivua ei ole saatavilla, sivu palautetaan päätasolle.",
    "CMS.RollbackToVersion": "Haluatko varmasti palauttaa #%s version tästä sivusta?",
    "CMS.ShowAsList": "Näytä alasivut listana",
    "CMS.ThisPageAndSubpages": "Tämä sivu ja alasivut",
    "CMS.ThisPageOnly": "Vain tämä sivu",
    "CMS.Unpublish": "Haluatko varmasti poistaa tämän sivun julkaisusta?\n\nTämä sivu on vielä saatavilla vedoksena rakennepuusta.",
    "CMS.UpdateURL": "Päivitä URL",
    "CMS.ViewPage": "Näytä"
});
}