// This file was generated by silverstripe/tx-translator from client/lang/src/hr.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('hr', {
    "CMS.ALERTCLASSNAME": "Tip stranice će biti osvježen nakon spremanja stranice",
    "CMS.AddSubPage": "Dodaj novu stranicu ovdje",
    "CMS.ConfirmRestoreFromLive": "Da li ste sigurni da želite vratiti predložak kada je stranica zadnji put objavljena?",
    "CMS.Duplicate": "Dupliciraj",
    "CMS.EditPage": "Uredi",
    "CMS.ONLYSELECTTWO": "Možete usporediti samo dvije verzije u isto vrijeme.",
    "CMS.Restore": "Da li ste sigurni da želite vratiti stranicu iz arhive?",
    "CMS.RestoreToRoot": "Jeste li sigurni da želite vratiti ovu stranicu iz arhive?\n\nNadstranica neće biti dostupna kada se stranica vrati.",
    "CMS.RollbackToVersion": "Jeste li sigurni da želite vratiti na verziju #%s ove stranice?",
    "CMS.ShowAsList": "Prikaži podstranice kao listu",
    "CMS.ThisPageAndSubpages": "Ova stranica i podstranice",
    "CMS.ThisPageOnly": "Samo ova stranica",
    "CMS.Unpublish": "Jeste li sigurni da želite ukloniti ovu stranicu iz objavljene stranice?\n\nOva stranica će ostati dostupna u stablu kao predložak.",
    "CMS.UpdateURL": "Ažuriraj link",
    "CMS.ViewPage": "Pregled"
});
}