// This file was generated by silverstripe/tx-translator from client/lang/src/hu.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('hu', {
    "CMS.ALERTCLASSNAME": "Az oldaltípust a mentést követően lesz beállítva",
    "CMS.AddSubPage": "Új oldal létrehozása ebben a mappában",
    "CMS.Duplicate": "Duplikál",
    "CMS.EditPage": "Szerkeszt",
    "CMS.RollbackToVersion": "Visszaállítja az oldal #%s verzióját?",
    "CMS.ShowAsList": "Gyerekoldalak lista nézetben",
    "CMS.ThisPageAndSubpages": "Csak ez az oldal és az alatta levő oldalak",
    "CMS.ThisPageOnly": "Csak ez az oldal"
});
}