// This file was generated by silverstripe/tx-translator from client/lang/src/id.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('id', {
    "CMS.ALERTCLASSNAME": "Jenis laman akan diperbarui setelah laman disimpan",
    "CMS.AddSubPage": "Tambah laman baru di sini",
    "CMS.Duplicate": "Gandakan",
    "CMS.RollbackToVersion": "Apakah Anda ingin kembali ke versi #%s dari laman ini?",
    "CMS.ShowAsList": "Tampilkan turunan sebagai daftar",
    "CMS.ThisPageAndSubpages": "Laman dan sublaman ini",
    "CMS.ThisPageOnly": "Hanya laman ini"
});
}