// This file was generated by silverstripe/tx-translator from client/lang/src/is.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('is', {
    "CMS.ALERTCLASSNAME": "Tegund siðu verður uppfært eftir vistun síðu",
    "CMS.AddSubPage": "Bæta við nýrri síðu hér",
    "CMS.Duplicate": "Fjölfalda",
    "CMS.EditPage": "Breyta",
    "CMS.ThisPageAndSubpages": "Þessi síða og undirsíður",
    "CMS.ThisPageOnly": "Aðeins þessi síða"
});
}