// This file was generated by silverstripe/cow from client/lang/src/is.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('is', {
    "CMS.ALERTCLASSNAME": "Tegund siðu verður uppfært eftir vistun síðu",
    "CMS.AddSubPage": "Bæta við nýrri síðu hér",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "Fjölfalda",
    "CMS.EditPage": "Breyta",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Do you really want to roll back to version #%s of this page?",
    "CMS.ShowAsList": "Show children as list",
    "CMS.ThisPageAndSubpages": "Þessi síða og undirsíður",
    "CMS.ThisPageOnly": "Aðeins þessi síða",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Update URL",
    "CMS.ViewPage": "View"
});
}