// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "CMS.ALERTCLASSNAME": "Il Tipo di pagina verrà aggiornato dopo che la pagina è stata salvata.",
    "CMS.AddSubPage": "Aggiungi una nuova pagina qui",
    "CMS.ConfirmRestoreFromLive": "Si è sicuri di voler ripristinare questa bozza all'ultima volta che è stata pubblicata?",
    "CMS.Duplicate": "Duplica",
    "CMS.EditPage": "Modifica",
    "CMS.Restore": "Si è sicuri di voler ripristinare questa pagina dall'archivio?",
    "CMS.RestoreToRoot": "Si è sicuri di voler ripristinare questa pagina dall'archivio?\n\nPoiché la pagina genitore non è disponibile, questo ripristinerà al primo livello.",
    "CMS.RollbackToVersion": "Vuoi veramente tornare alla versione #%s di questa pagina?",
    "CMS.ShowAsList": "Mostra figli come lista",
    "CMS.ThisPageAndSubpages": "Questa pagina e le sottopagine",
    "CMS.ThisPageOnly": "Solo questa pagina",
    "CMS.Unpublish": "Si è sicuri di voler eliminare la pagina dal sito pubblico?\n\nQuesta pagina sarà comunque disponibile nel SiteTree come bozza.",
    "CMS.UpdateURL": "Aggiornare l'URL",
    "CMS.ViewPage": "Visualizza"
});
}