// This file was generated by silverstripe/tx-translator from client/lang/src/ja.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ja', {
    "CMS.ALERTCLASSNAME": "ページ保存後にページの種類は更新されます．",
    "CMS.AddSubPage": "ここに新しいページを追加",
    "CMS.Duplicate": "重複",
    "CMS.EditPage": "編集",
    "CMS.RollbackToVersion": "このページのバージョン#%sへ本当にロールバックしますか?",
    "CMS.ShowAsList": "子どもをリストで表示する",
    "CMS.ThisPageAndSubpages": "このページとサブページ",
    "CMS.ThisPageOnly": "このページのみ"
});
}