// This file was generated by silverstripe/cow from client/lang/src/ja.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ja', {
    "CMS.ALERTCLASSNAME": "ページ保存後にページの種類は更新されます．",
    "CMS.AddSubPage": "ここに新しいページを追加",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "重複",
    "CMS.EditPage": "編集",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "このページのバージョン#%sへ本当にロールバックしますか?",
    "CMS.ShowAsList": "子どもをリストで表示する",
    "CMS.ThisPageAndSubpages": "このページとサブページ",
    "CMS.ThisPageOnly": "このページのみ",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Update URL",
    "CMS.ViewPage": "View"
});
}