// This file was generated by silverstripe/tx-translator from client/lang/src/lt.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('lt', {
    "CMS.ALERTCLASSNAME": "Puslapio tipas bus atnaujintas po išsaugojimo",
    "CMS.AddSubPage": "Pridėti naują puslapį čia",
    "CMS.ConfirmRestoreFromLive": "Ar tikrai norite atšaukti pakeitimus juodraštyje į paskutinę publikuotą versiją?",
    "CMS.Duplicate": "Kopijuoti",
    "CMS.EditPage": "Redaguoti",
    "CMS.Restore": "Ar tikrai norite atstatyti šį puslapį iš archyvo?",
    "CMS.RestoreToRoot": "Ar tikrai norite atstatyti šį puslapį iš archyvo?\n\nKadangi tėvinis puslapis neegzistuoja, šis puslapis bus atstatytas kaip aukščiausio lygio puslapis.",
    "CMS.RollbackToVersion": "Ar tikrai norite atstatyti šį puslapį į #%s versiją?",
    "CMS.ShowAsList": "Rodyti žemesnius pusl. kaip sąrašą",
    "CMS.ThisPageAndSubpages": "Šį puslapį ir visus po juo",
    "CMS.ThisPageOnly": "Tik šį puslapį",
    "CMS.Unpublish": "Ar tikrai norite pašalinti šį puslapį iš publikuotų puslapių?\n\nŠis puslapis liks puslapių medyje kaip juodraštinis.",
    "CMS.UpdateURL": "Atnaujinti URL dalį"
});
}