// This file was generated by silverstripe/cow from client/lang/src/mi.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('mi', {
    "CMS.ALERTCLASSNAME": "Ka whakahōutia te momo whārangi i muri i te tiaki i te whārangi",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Kei te tino hiahia hoki ki te tauira #%s o tēnei whārangi?",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.AddSubPage": "Tāpiri whārangi hou ki konei",
    "CMS.Duplicate": "Tārite",
    "CMS.EditPage": "Whakatika",
    "CMS.ShowAsList": "Whakaatu tamariki hei rārangi",
    "CMS.ThisPageAndSubpages": "Tēnei whārangi me ngā whārangi iti",
    "CMS.ThisPageOnly": "Tēnei whārangi anake",
    "CMS.ViewPage": "View",
    "CMS.UpdateURL": "Update URL",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time."
});
}