// This file was generated by silverstripe/tx-translator from client/lang/src/mi.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('mi', {
    "CMS.ALERTCLASSNAME": "Ka whakahōutia te momo whārangi i muri i te tiaki i te whārangi",
    "CMS.AddSubPage": "Tāpiri whārangi hou ki konei",
    "CMS.Duplicate": "Tārite",
    "CMS.EditPage": "Whakatika",
    "CMS.RollbackToVersion": "Kei te tino hiahia hoki ki te tauira #%s o tēnei whārangi?",
    "CMS.ShowAsList": "Whakaatu tamariki hei rārangi",
    "CMS.ThisPageAndSubpages": "Tēnei whārangi me ngā whārangi iti",
    "CMS.ThisPageOnly": "Tēnei whārangi anake"
});
}