// This file was generated by silverstripe/tx-translator from client/lang/src/nb.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nb', {
    "CMS.ALERTCLASSNAME": "Sidetypen vil bare bli oppdatert når siden blir lagret",
    "CMS.AddSubPage": "Legg til ny side her",
    "CMS.Duplicate": "Dupliser",
    "CMS.EditPage": "Rediger",
    "CMS.RollbackToVersion": "Vil du virkelig rulle tilbake til versjon #%s av denne siden?",
    "CMS.ShowAsList": "Vis undersider som en liste",
    "CMS.ThisPageAndSubpages": "Denne siden og undersider",
    "CMS.ThisPageOnly": "Bare denne siden"
});
}