// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "CMS.ALERTCLASSNAME": "Het paginatype wordt aangepast na het opslaan van de pagina",
    "CMS.AddSubPage": "Voeg nieuwe pagina toe",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "Dupliceren",
    "CMS.EditPage": "Aanpassen",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Wil je echt terugdraaien naar versie #%s van deze pagina?",
    "CMS.ShowAsList": "Toon onderliggende pagina's als lijst",
    "CMS.ThisPageAndSubpages": "Deze pagina en subpagina's",
    "CMS.ThisPageOnly": "Enkel deze pagina",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Update URL",
    "CMS.ViewPage": "View"
});
}