// This file was generated by silverstripe/cow from client/lang/src/pl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "CMS.ALERTCLASSNAME": "Ta strona zostanie zaktualizowana po jej zapisaniu",
    "CMS.AddSubPage": "Dodaj tutaj nową stronę",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "Powiel",
    "CMS.EditPage": "Edytuj",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Czy na pewno cofnąć do wersji #%s tej strony?",
    "CMS.ShowAsList": "Pokaż dzieci jako listę",
    "CMS.ThisPageAndSubpages": "Ta strona i podstrony",
    "CMS.ThisPageOnly": "Tylko tę stronę",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Update URL",
    "CMS.ViewPage": "View"
});
}