// This file was generated by silverstripe/tx-translator from client/lang/src/pl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "CMS.ALERTCLASSNAME": "Ta strona zostanie zaktualizowana po jej zapisaniu",
    "CMS.AddSubPage": "Dodaj tutaj nową stronę",
    "CMS.ConfirmRestoreFromLive": "Czy na pewno chcesz przywrócić wersję roboczą do daty ostatniej publikacji strony?",
    "CMS.Duplicate": "Powiel",
    "CMS.EditPage": "Edytuj",
    "CMS.ONLYSELECTTWO": "Możesz teraz porównać tylko dwie wersje.",
    "CMS.Restore": "Czy na pewno chcesz przywrócić tę stronę z archiwum?",
    "CMS.RestoreToRoot": "Czy na pewno chcesz przywrócić tę stronę z archiwum?\n\nPonieważ strona nadrzędna nie jest dostępna, zostanie przywrócona do najwyższego poziomu.",
    "CMS.RollbackToVersion": "Czy na pewno cofnąć do wersji #%s tej strony?",
    "CMS.ShowAsList": "Pokaż dzieci jako listę",
    "CMS.ThisPageAndSubpages": "Ta strona i podstrony",
    "CMS.ThisPageOnly": "Tylko tę stronę",
    "CMS.Unpublish": "Czy na pewno chcesz usunąć swoją stronę z opublikowanej strony?\n\nTa strona będzie nadal dostępna jako wersja robocza.",
    "CMS.UpdateURL": "Aktualizuj URL",
    "CMS.ViewPage": "Widok"
});
}