// This file was generated by silverstripe/tx-translator from client/lang/src/ro.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ro', {
    "CMS.ALERTCLASSNAME": "Tipul de pagină va fi actualizat după ce pagina este salvată",
    "CMS.AddSubPage": "Adăugaţi o nouă pagină aici",
    "CMS.Duplicate": "Copie",
    "CMS.EditPage": "Editare",
    "CMS.RollbackToVersion": "Doriţi revenirea la versiunea #%s a acestei pagini?",
    "CMS.ShowAsList": "Afişare fii în format listă",
    "CMS.ThisPageAndSubpages": "Această pagină cu subpagini",
    "CMS.ThisPageOnly": "Doar această pagină"
});
}