// This file was generated by silverstripe/cow from client/lang/src/ro.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ro', {
    "CMS.ALERTCLASSNAME": "Tipul de pagină va fi actualizat după ce pagina este salvată",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Doriţi revenirea la versiunea #%s a acestei pagini?",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.AddSubPage": "Adăugaţi o nouă pagină aici",
    "CMS.Duplicate": "Copie",
    "CMS.EditPage": "Editare",
    "CMS.ShowAsList": "Afişare fii în format listă",
    "CMS.ThisPageAndSubpages": "Această pagină cu subpagini",
    "CMS.ThisPageOnly": "Doar această pagină",
    "CMS.ViewPage": "View",
    "CMS.UpdateURL": "Update URL",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time."
});
}