// This file was generated by silverstripe/tx-translator from client/lang/src/ru.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "CMS.ALERTCLASSNAME": "Тип страницы будет изменён после её сохранения.",
    "CMS.AddSubPage": "Добавить новую страницу",
    "CMS.ConfirmRestoreFromLive": "Вы действительно хотите вернуть черновик к состоянию опубликованной версии?",
    "CMS.Duplicate": "Создать копию",
    "CMS.EditPage": "Редактировать",
    "CMS.ONLYSELECTTWO": "Вы можете сравнивать только две версии.",
    "CMS.Restore": "Вы действительно хотите восстановить эту страницу из архива?",
    "CMS.RestoreToRoot": "Вы уверены что хотите восстановить данную страницу из архива?\n\nПоскольку родительская страница недоступна данная страница будет восстановлена в корень сайта.",
    "CMS.RollbackToVersion": "Вы действительно хотите восстановить версию #%s этой страницы?",
    "CMS.ShowAsList": "Показать страницы в виде списка",
    "CMS.ThisPageAndSubpages": "Вместе с вложенными страницами",
    "CMS.ThisPageOnly": "Только этой страницы",
    "CMS.Unpublish": "Вы уверены что хотите удалить страницу с опубликованного сайта?\n\nСтраница останется в черновиках.",
    "CMS.UpdateURL": "Обновить URL",
    "CMS.ViewPage": "Просмотр"
});
}