// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "CMS.ALERTCLASSNAME": "Typ stránky bude aktualizovaný až bude stránka uložená",
    "CMS.AddSubPage": "Pridať novú stránku tu",
    "CMS.ConfirmRestoreFromLive": "Určite chcete obnoviť koncept do doby, kedy bola stránka naposledy zverejnená?",
    "CMS.Duplicate": "Duplikovať",
    "CMS.EditPage": "Editovať",
    "CMS.Restore": "Určite chcete obnoviť túto stánku z archívu?",
    "CMS.RestoreToRoot": "Určite chcete obnoviť túto stránku z archívu?\n\nPretože nadriadená stránka nie je k dispozícii, bude obnovena do najvyššej úrovne.",
    "CMS.RollbackToVersion": "Skutočne chcete vrátiť späť na verziu #%s tejto stránky?",
    "CMS.ShowAsList": "Zobraziť potomkov ako zoznam",
    "CMS.ThisPageAndSubpages": "Túto stránku a podstránky",
    "CMS.ThisPageOnly": "Iba túto stránku",
    "CMS.Unpublish": "Určite chcete odstrániť stránku zo zverejneného webu?\n\nTáto stránka bude stále k dispozícii v štruktúre webu ako koncept.",
    "CMS.UpdateURL": "Aktualizovať URL",
    "CMS.ViewPage": "Zobraziť"
});
}