// This file was generated by silverstripe/cow from client/lang/src/sl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "CMS.ALERTCLASSNAME": "Tipska stran bo posodobljena po shranjevanju strani",
    "CMS.AddSubPage": "Dodaj novo stran tukaj",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "Podvoji",
    "CMS.EditPage": "Uredi",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Obnovim na verzijo #%s te strani?",
    "CMS.ShowAsList": "Prikaži otroke kot seznam",
    "CMS.ThisPageAndSubpages": "To stran in podstrani",
    "CMS.ThisPageOnly": "Samo to stran",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Posodobi URL",
    "CMS.ViewPage": "Pogled"
});
}