// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "CMS.ALERTCLASSNAME": "Tipska stran bo posodobljena po shranjevanju strani",
    "CMS.AddSubPage": "Dodaj novo stran tukaj",
    "CMS.Duplicate": "Podvoji",
    "CMS.EditPage": "Uredi",
    "CMS.RollbackToVersion": "Obnovim na verzijo #%s te strani?",
    "CMS.ShowAsList": "Prikaži otroke kot seznam",
    "CMS.ThisPageAndSubpages": "To stran in podstrani",
    "CMS.ThisPageOnly": "Samo to stran",
    "CMS.UpdateURL": "Posodobi URL",
    "CMS.ViewPage": "Pogled"
});
}