// This file was generated by silverstripe/tx-translator from client/lang/src/sr.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr', {
    "CMS.ALERTCLASSNAME": "Тип странице ће бити ажуриран након што сачувате страницу",
    "CMS.AddSubPage": "Додај нову страницу овде",
    "CMS.Duplicate": "Дуплирај/копирај",
    "CMS.EditPage": "Измени",
    "CMS.RollbackToVersion": "Да ли заиста желите да се вратите на верзију  #%s ове странице?",
    "CMS.ShowAsList": "Прикажу децу у виду листе",
    "CMS.ThisPageAndSubpages": "Ова страница и подстранице",
    "CMS.ThisPageOnly": "Само ова страница"
});
}