// This file was generated by silverstripe/cow from client/lang/src/sr.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr', {
    "CMS.ALERTCLASSNAME": "Тип странице ће бити ажуриран након што сачувате страницу",
    "CMS.AddSubPage": "Додај нову страницу овде",
    "CMS.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMS.Duplicate": "Дуплирај/копирај",
    "CMS.EditPage": "Измени",
    "CMS.ONLYSELECTTWO": "You can only compare two versions at this time.",
    "CMS.Restore": "Are you sure you want to restore this page from archive?",
    "CMS.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMS.RollbackToVersion": "Да ли заиста желите да се вратите на верзију  #%s ове странице?",
    "CMS.ShowAsList": "Прикажу децу у виду листе",
    "CMS.ThisPageAndSubpages": "Ова страница и подстранице",
    "CMS.ThisPageOnly": "Само ова страница",
    "CMS.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "CMS.UpdateURL": "Update URL",
    "CMS.ViewPage": "View"
});
}