// This file was generated by silverstripe/tx-translator from client/lang/src/sr_RS@latin.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr_RS@latin', {
    "CMS.ALERTCLASSNAME": "Tip stranice će biti ažuriran nakon što sačuvate stranicu",
    "CMS.AddSubPage": "Dodaj novu stranicu ovde",
    "CMS.Duplicate": "Dupliraj/kopiraj",
    "CMS.EditPage": "Izmeni",
    "CMS.RollbackToVersion": "Da li zaista želite da se vratite na verziju  #%s ove stranice?",
    "CMS.ShowAsList": "Prikažu decu u vidu liste",
    "CMS.ThisPageAndSubpages": "Ova stranica i podstranice",
    "CMS.ThisPageOnly": "Samo ova stranica"
});
}