// This file was generated by silverstripe/tx-translator from client/lang/src/uk_UA.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('uk_UA', {
    "CMS.ALERTCLASSNAME": "Тип сторінки буде оновлено після збереження сторінки",
    "CMS.AddSubPage": "Додати нову сторінку тут",
    "CMS.ConfirmRestoreFromLive": "Ви впевнені, що хочете повернути чернетку до часу останньої публікації сторінки?",
    "CMS.Duplicate": "Дублікат",
    "CMS.EditPage": "Редагувати",
    "CMS.ONLYSELECTTWO": "Наразі можна порівняти лише дві версії.",
    "CMS.Restore": "Ви впевнені, що бажаєте відновити цю сторінку з архіву?",
    "CMS.RestoreToRoot": "Ви впевнені, що бажаєте відновити цю сторінку з архіву?\n\nОскільки батьківська сторінка недоступна, її буде відновлено до верхнього рівня.",
    "CMS.RollbackToVersion": "Ви справді бажаєте повернутися до версії #%s цієї сторінки?",
    "CMS.ShowAsList": "Показати дітей як список",
    "CMS.ThisPageAndSubpages": "Ця сторінка та підсторінки",
    "CMS.ThisPageOnly": "Тільки ця сторінка",
    "CMS.Unpublish": "Ви впевнені, що хочете видалити свою сторінку з опублікованого сайту?\n\nЦя сторінка все ще буде доступна в дереві сайту як чернетка.",
    "CMS.UpdateURL": "Оновити URL",
    "CMS.ViewPage": "Переглянути"
});
}