// This file was generated by silverstripe/tx-translator from client/lang/src/zh.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('zh', {
    "CMS.ALERTCLASSNAME": "将在页面保存后上传页面类型",
    "CMS.AddSubPage": "在此添加新页面",
    "CMS.Duplicate": "复制",
    "CMS.EditPage": "编辑",
    "CMS.RollbackToVersion": "是否确定回滚至该页面的第 #%s 版？",
    "CMS.ShowAsList": "将儿童显示为列表",
    "CMS.ThisPageAndSubpages": "本页和子页面",
    "CMS.ThisPageOnly": "仅该页"
});
}