// This file was generated by silverstripe/cow from javascript/lang/src/ar.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ar', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "هل تريد حقًا حذف مجلدات %s؟",
    "AssetAdmin.ConfirmDelete": "هل تريد حقًا حذف هذا المجلد وكل ما يحتويه من ملفات؟",
    "AssetTableField.MOVING": "تم نقل %s من الملفات",
    "AssetTableField.REALLYDELETE": "هل تريد حقًا حذف الملفات المعلّمة؟",
    "CMSMAIN.ALERTCLASSNAME": "سيتم تحديث نوع الصفحة بعد حفظ الصفحة",
    "CMSMAIN.AddSearchCriteria": "إضافة معيار",
    "CMSMAIN.CANTADDCHILDREN": "لا يمكنك إضافة التوابع إلى العقدة المحددة",
    "CMSMAIN.DELETINGPAGES": "جاري حذف الصفحات...",
    "CMSMAIN.ERRORADDINGPAGE": "حدث خطأ في إضافة صفحة",
    "CMSMAIN.ERRORDELETINGPAGES": "خطأ أثناء حذف الصفحات",
    "CMSMAIN.ERRORFILTERPAGES": "لا يمكن تصنيف المسار الشجري حتى يُظهر الصفحات التي تم تغييرها فقط<br /> %s",
    "CMSMAIN.ERRORPUBLISHING": "خطأ في الصحات المنشورة",
    "CMSMAIN.ERRORREVERTING": "خطأ أثناء العودة إلى المحتوى المباشر",
    "CMSMAIN.ERRORUNFILTER": "شجرة غير مصفّاة",
    "CMSMAIN.FILTEREDTREE": "شجرة مصفّاة فقط لإظهار الصفحات التي تم تغييرها",
    "CMSMAIN.PUBLISHING": "جاري النشر...",
    "CMSMAIN.PUBLISHINGPAGES": "جاري نشر الصفحات...",
    "CMSMAIN.REALLYDELETEPAGES": "هل ترغب حقًا في حذف الصفحات %s المعلّمة؟",
    "CMSMAIN.RESTORING": "جاري الاستعادة...",
    "CMSMAIN.SAVING": "جاري الحذف...",
    "CMSMAIN.SELECTMOREPAGES": "لقد قمت باختيار عدد %s من الصفحات.\n\nهل تريد حقاً تنفيذ هذا الإجراء؟",
    "CMSMAIN.SELECTONEPAGE": "يرجى تحديد صفحة واحدة على الأقل.",
    "CMSMAIN.URLSEGMENTVALIDATION": "يمكن تكوين عناوين URL من أحرف وأرقام وواصلات فقط.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "يجب عليك حفظ إحدى الصفحات قبل إضافة أطفال تحته",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "هل تريد حقاً الرجوع إلى النسخة #%s من هذه الصفحة؟",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "اسم المجلد",
    "Tree.AddSubPage": "أضف صفحة جديدة هنا",
    "Tree.Duplicate": "تكرار",
    "Tree.EditPage": "تحرير",
    "Tree.ShowAsList": "أعرض التوابع في شكل قائمة",
    "Tree.ThisPageAndSubpages": "هذه الصفحة وصفحات فرعية",
    "Tree.ThisPageOnly": "هذه الصفحة فقط",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "إلغاء",
    "URLSEGMENT.Edit": "تحرير",
    "URLSEGMENT.OK": "موافق",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "عفواً، لقد وصلت للحد الأقصى لعدد التطبيقات المصغرة في هذه المنطقة"
});
}