// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ar.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ar', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "يجب عليك حفظ إحدى الصفحات قبل إضافة أطفال تحته",
    "CMSMAIN.CANTADDCHILDREN": "لا يمكنك إضافة التوابع إلى العقدة المحددة",
    "CMSMAIN.ERRORADDINGPAGE": "حدث خطأ في إضافة صفحة",
    "CMSMAIN.FILTEREDTREE": "شجرة مصفّاة فقط لإظهار الصفحات التي تم تغييرها",
    "CMSMAIN.ERRORFILTERPAGES": "لا يمكن تصنيف المسار الشجري حتى يُظهر الصفحات التي تم تغييرها فقط<br /> %s",
    "CMSMAIN.ERRORUNFILTER": "شجرة غير مصفّاة",
    "CMSMAIN.PUBLISHINGPAGES": "جاري نشر الصفحات...",
    "CMSMAIN.SELECTONEPAGE": "يرجى تحديد صفحة واحدة على الأقل.",
    "CMSMAIN.ERRORPUBLISHING": "خطأ في الصحات المنشورة",
    "CMSMAIN.REALLYDELETEPAGES": "هل ترغب حقًا في حذف الصفحات %s المعلّمة؟",
    "CMSMAIN.DELETINGPAGES": "جاري حذف الصفحات...",
    "CMSMAIN.ERRORDELETINGPAGES": "خطأ أثناء حذف الصفحات",
    "CMSMAIN.PUBLISHING": "جاري النشر...",
    "CMSMAIN.RESTORING": "جاري الاستعادة...",
    "CMSMAIN.ERRORREVERTING": "خطأ أثناء العودة إلى المحتوى المباشر",
    "CMSMAIN.SAVING": "جاري الحذف...",
    "CMSMAIN.SELECTMOREPAGES": "لقد قمت باختيار عدد %s من الصفحات.\n\nهل تريد حقاً تنفيذ هذا الإجراء؟",
    "CMSMAIN.ALERTCLASSNAME": "سيتم تحديث نوع الصفحة بعد حفظ الصفحة",
    "CMSMAIN.URLSEGMENTVALIDATION": "يمكن تكوين عناوين URL من أحرف وأرقام وواصلات فقط.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "هل تريد حقًا حذف مجلدات %s؟",
    "AssetTableField.REALLYDELETE": "هل تريد حقًا حذف الملفات المعلّمة؟",
    "AssetTableField.MOVING": "تم نقل %s من الملفات",
    "CMSMAIN.AddSearchCriteria": "إضافة معيار",
    "WidgetAreaEditor.TOOMANY": "عفواً، لقد وصلت للحد الأقصى لعدد التطبيقات المصغرة في هذه المنطقة",
    "AssetAdmin.ConfirmDelete": "هل تريد حقًا حذف هذا المجلد وكل ما يحتويه من ملفات؟",
    "Folder.Name": "اسم المجلد",
    "Tree.AddSubPage": "أضف صفحة جديدة هنا",
    "Tree.Duplicate": "تكرار",
    "Tree.EditPage": "تحرير",
    "Tree.ThisPageOnly": "هذه الصفحة فقط",
    "Tree.ThisPageAndSubpages": "هذه الصفحة وصفحات فرعية",
    "Tree.ShowAsList": "أعرض التوابع في شكل قائمة",
    "CMSMain.ConfirmRestoreFromLive": "هل ترغب حقًا في نسخ المحتوى المنشور على مسودة الموقع؟",
    "CMSMain.RollbackToVersion": "هل تريد حقاً الرجوع إلى النسخة #%s من هذه الصفحة؟",
    "URLSEGMENT.Edit": "تحرير",
    "URLSEGMENT.OK": "موافق",
    "URLSEGMENT.Cancel": "إلغاء"
});
}