// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/cs.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('cs', {
    "CMSMAIN.ALERTCLASSNAME": "Typ stránky bude aktualizován až stránka bude uložena",
    "CMSMain.RollbackToVersion": "Skutečně chcete vrátit zpět na verzi #%s této stránky?",
    "CMSMAIN.CANTADDCHILDREN": "Nemůžete přidat potomky do vybraného uzlu",
    "CMSMAIN.PUBLISHINGPAGES": "Zveřejňování stránek...",
    "CMSMAIN.SELECTMOREPAGES": "Máte vybráno %s stránek.\n\nSkutečně je chcete?",
    "CMSMAIN.SAVING": "ukládání...",
    "CMSMAIN.ERRORDELETINGPAGES": "Chyba při mazání stránek",
    "URLSEGMENT.Edit": "Editovat",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Před přidáním další podstránky, musíte stránku uložit",
    "CMSMAIN.PUBLISHING": "Zveřejňování...",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs múže být vytvořeno pouze znaky, čísly a spojovníky.",
    "URLSEGMENT.Cancel": "Storno",
    "Tree.ShowAsList": "Zobrazit potomky jako seznam",
    "CMSMAIN.ERRORREVERTING": "Chyba převádění na živý obsah",
    "Tree.ThisPageOnly": "Pouze tuto stránku",
    "CMSMain.ConfirmRestoreFromLive": "Skutečně chcete zkopírovat zveřejněn obsah do konceptu?",
    "CMSMAIN.ERRORPUBLISHING": "Chyba při zveřejňování stránek",
    "CMSMAIN.ERRORADDINGPAGE": "Chyba při přidání stránky",
    "AssetTableField.REALLYDELETE": "Skuečně chcete smazat označené soubory?",
    "CMSMAIN.RESTORING": "Obnovování...",
    "AssetTableField.MOVING": "Přemísťování %s soubor(ů)",
    "Tree.EditPage": "Editovat",
    "URLSEGMENT.OK": "OK",
    "CMSMAIN.ERRORUNFILTER": "Nefiltrovaná struktura",
    "CMSMAIN.FILTEREDTREE": "Filtrovaná struktura k zobrazení pouze zmeněných stránek",
    "AssetAdmin.ConfirmDelete": "Skutečně chcete smazat tuto složku a všechny obsahující soubory?",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Skutečně chcete smazat %s složky?",
    "CMSMAIN.AddSearchCriteria": "Přidat kritéria",
    "Tree.Duplicate": "Duplikovat",
    "Tree.ThisPageAndSubpages": "Tuto stránku a podstránky",
    "WidgetAreaEditor.TOOMANY": "Promiňte, dosáhl jste maximální počet widgetů v této oblasti",
    "CMSMAIN.DELETINGPAGES": "Mazání stránek...",
    "Folder.Name": "Název složky",
    "CMSMAIN.REALLYDELETEPAGES": "Skutečně chcete smazat %s označené stránky?",
    "CMSMAIN.SELECTONEPAGE": "Prosím, vyberte nejméně 1 stránku.",
    "Tree.AddSubPage": "Přidat novou stránku sem",
    "CMSMAIN.ERRORFILTERPAGES": "Není možno filtrovat strukturu k zobrazení pouze zmeněných stránek<br />%s"
});
}