// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/eo.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('eo', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Necesas konservi paĝon antaŭ ol enmeti idojn sub ĝi",
    "CMSMAIN.CANTADDCHILDREN": "Vi ne povas aldoni idojn al la elektita nodo",
    "CMSMAIN.ERRORADDINGPAGE": "Eraro okazis enmetante paĝon",
    "CMSMAIN.FILTEREDTREE": "Filtrita arbo vidigu nur ŝanĝitajn paĝojn",
    "CMSMAIN.ERRORFILTERPAGES": "Ne eblis filtri la arbon por vidigi nur ŝanĝitajn paĝojn<br />%s",
    "CMSMAIN.ERRORUNFILTER": "Nefiltrita arbo",
    "CMSMAIN.PUBLISHINGPAGES": "Publikigas paĝojn...",
    "CMSMAIN.SELECTONEPAGE": "Bonvole elektu almenaŭ 1 paĝon.",
    "CMSMAIN.ERRORPUBLISHING": "Eraro okazis publikigante paĝojn",
    "CMSMAIN.REALLYDELETEPAGES": "Ĉu vi vere volas forigi la %s markitajn paĝojn?",
    "CMSMAIN.DELETINGPAGES": "Forigas paĝojn...",
    "CMSMAIN.ERRORDELETINGPAGES": "Eraro okazis forigante paĝojn",
    "CMSMAIN.PUBLISHING": "Publikigas...",
    "CMSMAIN.RESTORING": "Restaŭras...",
    "CMSMAIN.ERRORREVERTING": "Okazis eraro anstataŭigante per publika enhavo",
    "CMSMAIN.SAVING": "konservas...",
    "CMSMAIN.SELECTMOREPAGES": "Vi elektis %s paĝojn.\n\nĈu vi vere volas fari tiun agon?",
    "CMSMAIN.ALERTCLASSNAME": "La paĝotipo aktualiĝos kiam la paĝo estas konservita",
    "CMSMAIN.URLSEGMENTVALIDATION": "URL konsistu el literoj, ciferoj kaj streketoj.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Ĉi vi vere volas forigi %s dosierujojn?",
    "AssetTableField.REALLYDELETE": "Ĉu vi vere volas forigi la markitajn dosierojn?",
    "AssetTableField.MOVING": "Movas %s dosiero(j)n",
    "CMSMAIN.AddSearchCriteria": "Aldoni kriteriojn",
    "WidgetAreaEditor.TOOMANY": "Bedaŭrinde vi atingis la maksimuman nombron da fenestraĵoj por la zono",
    "AssetAdmin.ConfirmDelete": "Ĉu vi vere volas forigi ĉi tiun dosierujon kaj ĉiujn dosierojn en ĝi?",
    "Folder.Name": "Nomo de dosierujo",
    "Tree.AddSubPage": "Aldoni novan paĝon ĉi tie",
    "Tree.Duplicate": "Duobligi",
    "Tree.EditPage": "Redakti",
    "Tree.ThisPageOnly": "Nur ĉi tiu paĝo",
    "Tree.ThisPageAndSubpages": "Ĉi tiu paĝo kaj subpaĝoj",
    "Tree.ShowAsList": "Vidigi idojn kiel liston",
    "CMSMain.ConfirmRestoreFromLive": "Ĉu vi vere volas kopii la publikigitan enhavon al la malneta retejo?",
    "CMSMain.RollbackToVersion": "Cu vi vere volas malfare restaŭri al versio #%s de ĉi tiu paĝo?",
    "URLSEGMENT.Edit": "Redakti",
    "URLSEGMENT.OK": "Akcepti",
    "URLSEGMENT.Cancel": "Rezigni"
});
}