// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/fi.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('fi', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Sinun on tallennettava sivu, ennen kuin voi lisätä alasivuja",
    "CMSMAIN.CANTADDCHILDREN": "Et voi lisätä alasivuja tähän solmuun",
    "CMSMAIN.ERRORADDINGPAGE": "Virhe lisättäessä sivua",
    "CMSMAIN.FILTEREDTREE": "Suodatettu puu, joka näyttää vain muuttuneet sivut",
    "CMSMAIN.ERRORFILTERPAGES": "Ei voitu suodattaa hakemistopuuta näyttämään vain muuttuneet sivut<br />%s",
    "CMSMAIN.ERRORUNFILTER": "Suodattamaton hakemistopuu",
    "CMSMAIN.PUBLISHINGPAGES": "Julkaistaan sivuja...",
    "CMSMAIN.SELECTONEPAGE": "Valitse vähintään 1 sivu.",
    "CMSMAIN.ERRORPUBLISHING": "Tapahtui virhe julkaistaessa sivuja",
    "CMSMAIN.REALLYDELETEPAGES": "Haluatko varmasti poistaa %s kpl merkittyjä sivuja?",
    "CMSMAIN.DELETINGPAGES": "Poistetaan sivuja...",
    "CMSMAIN.ERRORDELETINGPAGES": "Tapahtui virhe poistettaessa sivuja",
    "CMSMAIN.PUBLISHING": "Julkaistaan...",
    "CMSMAIN.RESTORING": "Palautetaan...",
    "CMSMAIN.ERRORREVERTING": "Tapahtui virhe paluussa julkaistuun sisältöön",
    "CMSMAIN.SAVING": "tallennetaan...",
    "CMSMAIN.SELECTMOREPAGES": "Sinulla on %s sivua valittuna.\n\nHaluatko varmasti tehdä tämän toiminnon?",
    "CMSMAIN.ALERTCLASSNAME": "Sivutyyppi päivitetään sivun tallennuksen jälkeen",
    "CMSMAIN.URLSEGMENTVALIDATION": "URL-osoitteet voivat muodostua vain kirjaimista, numeroista tai yhdysmerkeistä.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Haluatko varmasti poistaa %s kansion/kansiota?",
    "AssetTableField.REALLYDELETE": "Haluatko varmasti poistaa merkityt tiedostot?",
    "AssetTableField.MOVING": "Siirretään %s tiedosto(a)",
    "CMSMAIN.AddSearchCriteria": "Lisää kriteeri",
    "WidgetAreaEditor.TOOMANY": "Pahoittelut, olet lisännyt sallitun maksimi määrän vimpaimia tälle alueelle.",
    "AssetAdmin.ConfirmDelete": "Haluatko varmasti poistaa tämän kansion ja kaikki tiedostot sen sisällä?",
    "Folder.Name": "Kansion nimi",
    "Tree.AddSubPage": "Lisää uusi sivu tähän",
    "Tree.Duplicate": "Monista",
    "Tree.EditPage": "Muokkaa",
    "Tree.ThisPageOnly": "Vain tämä sivu",
    "Tree.ThisPageAndSubpages": "Tämä sivu ja alasivut",
    "Tree.ShowAsList": "Näytä alasivut listana",
    "CMSMain.ConfirmRestoreFromLive": "Haluatko varmasti kopioida julkaistua sisältöä luonnossivustolle?",
    "CMSMain.RollbackToVersion": "Haluatko varmasti palauttaa #%s version tästä sivusta?",
    "URLSEGMENT.Edit": "Muokkaa",
    "URLSEGMENT.OK": "OK",
    "URLSEGMENT.Cancel": "Peruuta"
});
}