// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/id.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('id', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "You have to save a page before adding children underneath it",
    "CMSMAIN.CANTADDCHILDREN": "You can't add children to the selected node",
    "CMSMAIN.ERRORADDINGPAGE": "Error adding page",
    "CMSMAIN.FILTEREDTREE": "Filtered tree to only show changed pages",
    "CMSMAIN.ERRORFILTERPAGES": "Could not filter tree to only show changed pages<br />%s",
    "CMSMAIN.ERRORUNFILTER": "Unfiltered tree",
    "CMSMAIN.PUBLISHINGPAGES": "Publishing pages...",
    "CMSMAIN.SELECTONEPAGE": "Mohon pilih minimal 1 halaman.",
    "CMSMAIN.ERRORPUBLISHING": "Error publishing pages",
    "CMSMAIN.REALLYDELETEPAGES": "Do you really want to delete the %s marked pages?",
    "CMSMAIN.DELETINGPAGES": "Sedang menghapus halaman...",
    "CMSMAIN.ERRORDELETINGPAGES": "Error deleting pages",
    "CMSMAIN.PUBLISHING": "Publishing...",
    "CMSMAIN.RESTORING": "Sedang pemulihan",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "CMSMAIN.SAVING": "Sedang menyimpan...",
    "CMSMAIN.SELECTMOREPAGES": "You have %s pages selected.\n\nDo you really want to perform this action?",
    "CMSMAIN.ALERTCLASSNAME": "The page type will be updated after the page is saved",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs can only be made up of letters, digits and hyphens.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Apakah kamu yakin akan menghapus %s map?",
    "AssetTableField.REALLYDELETE": "Do you really want to delete the marked files?",
    "AssetTableField.MOVING": "Memindahkan %s berkas(s)",
    "CMSMAIN.AddSearchCriteria": "Tambah kriteria",
    "WidgetAreaEditor.TOOMANY": "Sorry, you have reached the maximum number of widgets in this area",
    "AssetAdmin.ConfirmDelete": "Do you really want to delete this folder and all contained files?",
    "Folder.Name": "Nama map",
    "Tree.AddSubPage": "Tambah halaman baru di sini",
    "Tree.Duplicate": "Duplikasi",
    "Tree.EditPage": "Ubah",
    "Tree.ThisPageOnly": "Hanya halaman ini",
    "Tree.ThisPageAndSubpages": "This page and subpages",
    "Tree.ShowAsList": "Show children as list",
    "CMSMain.ConfirmRestoreFromLive": "Do you really want to copy the published content to the draft site?",
    "CMSMain.RollbackToVersion": "Do you really want to roll back to version #%s of this page?",
    "URLSEGMENT.Edit": "Ubah",
    "URLSEGMENT.OK": "Oke",
    "URLSEGMENT.Cancel": "Batal"
});
}