// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/is.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('is', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Þú verður að vista síðuna áður bætt er við einhverju undir hana",
    "CMSMAIN.CANTADDCHILDREN": "You can't add children to the selected node",
    "CMSMAIN.ERRORADDINGPAGE": "Vandamál kom upp við að bæta við síðu",
    "CMSMAIN.FILTEREDTREE": "Filterað tré til að sýna aðeins breyttar síður",
    "CMSMAIN.ERRORFILTERPAGES": "Gat ekki flokkað tréið til að sýna aðeins breyttar síður<br/>%s° ",
    "CMSMAIN.ERRORUNFILTER": "Óflokkað tré",
    "CMSMAIN.PUBLISHINGPAGES": "Birti síður...",
    "CMSMAIN.SELECTONEPAGE": "Please select at least 1 page.",
    "CMSMAIN.ERRORPUBLISHING": "Villa kom við birtingu síðu",
    "CMSMAIN.REALLYDELETEPAGES": "Ertu viss um að þú viljir eyða %s  merktum síðum?",
    "CMSMAIN.DELETINGPAGES": "Eyði síðum...",
    "CMSMAIN.ERRORDELETINGPAGES": "Vandamál kom upp við eyðingu síðna",
    "CMSMAIN.PUBLISHING": "Birti...",
    "CMSMAIN.RESTORING": "Endurvek...",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "CMSMAIN.SAVING": "vista...",
    "CMSMAIN.SELECTMOREPAGES": "Þú hefur valið %s síður.\n\nErtu viss um að þú viljir halda áfram?",
    "CMSMAIN.ALERTCLASSNAME": "Tegund siðu verður uppfært eftir vistun síðu",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs can only be made up of letters, digits and hyphens.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Ertu viss um að þú viljir eyða %s möppunni?",
    "AssetTableField.REALLYDELETE": "Ertu viss um að þú viljir eyða merktum skrám?",
    "AssetTableField.MOVING": "Færi %s skrá(r)",
    "CMSMAIN.AddSearchCriteria": "Add Criteria",
    "WidgetAreaEditor.TOOMANY": "Sorry, you have reached the maximum number of widgets in this area",
    "AssetAdmin.ConfirmDelete": "Ertu viss um að þú viljir eyða þessari möppu og skrám sem tilheyra henni",
    "Folder.Name": "Nafn möppu",
    "Tree.AddSubPage": "Bæta við nýrri síðu hér",
    "Tree.Duplicate": "Fjölfalda",
    "Tree.EditPage": "Breyta",
    "Tree.ThisPageOnly": "Aðeins þessi síða",
    "Tree.ThisPageAndSubpages": "Þessi síða og undirsíður",
    "Tree.ShowAsList": "Show children as list",
    "CMSMain.ConfirmRestoreFromLive": "Ertu viss um að þú viljir afrita birt efni yfir á drög?",
    "CMSMain.RollbackToVersion": "Do you really want to roll back to version #%s of this page?",
    "URLSEGMENT.Edit": "Breyta",
    "URLSEGMENT.OK": "Allt í lagi",
    "URLSEGMENT.Cancel": "Hætta við"
});
}