// This file was generated by silverstripe/cow from javascript/lang/src/is.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('is', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Ertu viss um að þú viljir eyða %s möppunni?",
    "AssetAdmin.ConfirmDelete": "Ertu viss um að þú viljir eyða þessari möppu og skrám sem tilheyra henni",
    "AssetTableField.MOVING": "Færi %s skrá(r)",
    "AssetTableField.REALLYDELETE": "Ertu viss um að þú viljir eyða merktum skrám?",
    "CMSMAIN.ALERTCLASSNAME": "Tegund siðu verður uppfært eftir vistun síðu",
    "CMSMAIN.AddSearchCriteria": "Add Criteria",
    "CMSMAIN.CANTADDCHILDREN": "You can't add children to the selected node",
    "CMSMAIN.DELETINGPAGES": "Eyði síðum...",
    "CMSMAIN.ERRORADDINGPAGE": "Vandamál kom upp við að bæta við síðu",
    "CMSMAIN.ERRORDELETINGPAGES": "Vandamál kom upp við eyðingu síðna",
    "CMSMAIN.ERRORFILTERPAGES": "Gat ekki flokkað tréið til að sýna aðeins breyttar síður<br/>%s° ",
    "CMSMAIN.ERRORPUBLISHING": "Villa kom við birtingu síðu",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "CMSMAIN.ERRORUNFILTER": "Óflokkað tré",
    "CMSMAIN.FILTEREDTREE": "Filterað tré til að sýna aðeins breyttar síður",
    "CMSMAIN.PUBLISHING": "Birti...",
    "CMSMAIN.PUBLISHINGPAGES": "Birti síður...",
    "CMSMAIN.REALLYDELETEPAGES": "Ertu viss um að þú viljir eyða %s  merktum síðum?",
    "CMSMAIN.RESTORING": "Endurvek...",
    "CMSMAIN.SAVING": "vista...",
    "CMSMAIN.SELECTMOREPAGES": "Þú hefur valið %s síður.\n\nErtu viss um að þú viljir halda áfram?",
    "CMSMAIN.SELECTONEPAGE": "Please select at least 1 page.",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs can only be made up of letters, digits and hyphens.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Þú verður að vista síðuna áður bætt er við einhverju undir hana",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "Do you really want to roll back to version #%s of this page?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "Nafn möppu",
    "Tree.AddSubPage": "Bæta við nýrri síðu hér",
    "Tree.Duplicate": "Fjölfalda",
    "Tree.EditPage": "Breyta",
    "Tree.ShowAsList": "Show children as list",
    "Tree.ThisPageAndSubpages": "Þessi síða og undirsíður",
    "Tree.ThisPageOnly": "Aðeins þessi síða",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "Hætta við",
    "URLSEGMENT.Edit": "Breyta",
    "URLSEGMENT.OK": "Allt í lagi",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "Sorry, you have reached the maximum number of widgets in this area"
});
}