// This file was generated by silverstripe/cow from javascript/lang/src/ja.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ja', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "%sフォルダを本当に削除しますか?",
    "AssetAdmin.ConfirmDelete": "このフォルダとフォルダに含まれるすべてのファイルを本当に削除しますか?",
    "AssetTableField.MOVING": "%sファイルを移動中．",
    "AssetTableField.REALLYDELETE": "マークされているファイルを本当に削除しますか?",
    "CMSMAIN.ALERTCLASSNAME": "ページ保存後にページの種類は更新されます．",
    "CMSMAIN.AddSearchCriteria": "Add Criteria",
    "CMSMAIN.CANTADDCHILDREN": "選択されたノードには子供を追加することはできません．",
    "CMSMAIN.DELETINGPAGES": "ページを削除しています",
    "CMSMAIN.ERRORADDINGPAGE": "ページの追加でエラーが起きました．",
    "CMSMAIN.ERRORDELETINGPAGES": "ページ削除においてエラー",
    "CMSMAIN.ERRORFILTERPAGES": "変更されたページのみ表示するようにツリーをフィルタできませんでした<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "ページを公開中にエラー",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "CMSMAIN.ERRORUNFILTER": "フィルタされていないツリー",
    "CMSMAIN.FILTEREDTREE": "変更されたページのみ表示するフィルタされたツリー",
    "CMSMAIN.PUBLISHING": "公開しています...",
    "CMSMAIN.PUBLISHINGPAGES": "ページを公開しています...",
    "CMSMAIN.REALLYDELETEPAGES": "Do you really want to delete the %s marked pages?",
    "CMSMAIN.RESTORING": "復元しています...",
    "CMSMAIN.SAVING": "保存しています...",
    "CMSMAIN.SELECTMOREPAGES": "You have %s pages selected.\n\nDo you really want to perform this action?",
    "CMSMAIN.SELECTONEPAGE": "最低でも1ページ選択してください．",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLはアルファベットの文字か数値，及びハイフンのみから構成されます．",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "子ページを追加する前に，そのページを保存する必要があります．",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "このページのバージョン#%sへ本当にロールバックしますか?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "フォルダ名",
    "Tree.AddSubPage": "ここに新しいページを追加",
    "Tree.Duplicate": "重複",
    "Tree.EditPage": "編集",
    "Tree.ShowAsList": "子どもをリストで表示する",
    "Tree.ThisPageAndSubpages": "このページとサブページ",
    "Tree.ThisPageOnly": "このページのみ",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "キャンセル",
    "URLSEGMENT.Edit": "編集",
    "URLSEGMENT.OK": "OK",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "申し訳ございません．このエリアにおけるウィジェットの最大数に到達しました．"
});
}