// This file was generated by silverstripe/cow from javascript/lang/src/ko.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ko', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "%s 폴더를 정말 삭제합니까?",
    "AssetAdmin.ConfirmDelete": "이 폴더와 폴더에 포함된 모든 파일을 정말 삭제합니까?",
    "AssetTableField.MOVING": "%s 파일을 이동 중입니다.",
    "AssetTableField.REALLYDELETE": "표시된 파일을 정말 삭제합니까?",
    "CMSMAIN.ALERTCLASSNAME": "페이지 저장 후 페이지의 종류는 업데이트됩니다.",
    "CMSMAIN.AddSearchCriteria": "카테고리 추가",
    "CMSMAIN.CANTADDCHILDREN": "선택된 노드에 하위로 추가할 수 없습니다.",
    "CMSMAIN.DELETINGPAGES": "페이지를 삭제합니다",
    "CMSMAIN.ERRORADDINGPAGE": "페이지 추가에서 오류가 발생했습니다.",
    "CMSMAIN.ERRORDELETINGPAGES": "페이지 삭제에서 오류",
    "CMSMAIN.ERRORFILTERPAGES": "변경된 페이지만 표시하도록 트리를 필터링할 수 없습니다 <br />%s",
    "CMSMAIN.ERRORPUBLISHING": "페이지를 게시하는 동안 오류",
    "CMSMAIN.ERRORREVERTING": "라이브 컨텐츠로 전환과정에서 오류",
    "CMSMAIN.ERRORUNFILTER": "필터링안된 트리",
    "CMSMAIN.FILTEREDTREE": "변경된 페이지만 표시하는 필터링된 트리",
    "CMSMAIN.PUBLISHING": "공개하고 있습니다 ...",
    "CMSMAIN.PUBLISHINGPAGES": "페이지를 공개하고 있습니다 ...",
    "CMSMAIN.REALLYDELETEPAGES": "표시된 페이지 %s를 정말 삭제합니까?",
    "CMSMAIN.RESTORING": "복원하고 있습니다 ...",
    "CMSMAIN.SAVING": "저장하고 있습니다 ...",
    "CMSMAIN.SELECTMOREPAGES": "%s 페이지들이 선택되었습니다. \n\n계속하시겠습니까?",
    "CMSMAIN.SELECTONEPAGE": "최소한 1 페이지 선택하십시오.",
    "CMSMAIN.URLSEGMENTVALIDATION": "URL은 알파벳 문자나 숫자, 하이픈만으로 구성됩니다.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "하위 페이지를 추가하기 전에 페이지를 저장해야합니다.",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "이 페이지의 #%s 버젼으로 롤백하시겠습니까?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "폴더 이름",
    "Tree.AddSubPage": "여기에 새 페이지를 추가하기",
    "Tree.Duplicate": "중복",
    "Tree.EditPage": "편집",
    "Tree.ShowAsList": "하위 목록으로 표시",
    "Tree.ThisPageAndSubpages": "이 페이지와 하위 페이지",
    "Tree.ThisPageOnly": "이 페이지만",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "취소",
    "URLSEGMENT.Edit": "편집",
    "URLSEGMENT.OK": "OK",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "죄송합니다. 이 분야에서의 위젯의 최대수에 도달했습니다."
});
}