// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/lt.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('lt', {
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Privalote išsaugoti puslapį prieš sukuriant naujus puslapius po juo",
    "CMSMAIN.CANTADDCHILDREN": "Negalite sukurti po pasirinktu įrašu",
    "CMSMAIN.ERRORADDINGPAGE": "Klaida pridedant puslapį",
    "CMSMAIN.FILTEREDTREE": "Atfiltruotas medis, rodantis tik pakeistus puslapius",
    "CMSMAIN.ERRORFILTERPAGES": "Nepavyko atfiltruoti medžio, norint parodyti tik pakeistus puslapius<br />%s",
    "CMSMAIN.ERRORUNFILTER": "Neatfiltruotas medis",
    "CMSMAIN.PUBLISHINGPAGES": "Puslapiai publikuojami...",
    "CMSMAIN.SELECTONEPAGE": "Prašome pasirinkti bent 1 puslapį.",
    "CMSMAIN.ERRORPUBLISHING": "Klaida publikuojant puslapius",
    "CMSMAIN.REALLYDELETEPAGES": "Ar tikrai norite ištrinti %s pažymėtus puslapius?",
    "CMSMAIN.DELETINGPAGES": "Puslapiai trinami...",
    "CMSMAIN.ERRORDELETINGPAGES": "Klaida trinant puslapius",
    "CMSMAIN.PUBLISHING": "Publikuojama...",
    "CMSMAIN.RESTORING": "Atstatoma...",
    "CMSMAIN.ERRORREVERTING": "Klaida perjungiant turinį",
    "CMSMAIN.SAVING": "saugoma...",
    "CMSMAIN.SELECTMOREPAGES": "Pažymėjote %s puslapius.\n\nAr tikrai norite atlikti šį veiksmą?",
    "CMSMAIN.ALERTCLASSNAME": "Puslapio tipas bus atnaujintas po išsaugojimo",
    "CMSMAIN.URLSEGMENTVALIDATION": "URL dalis gali būti sudaryta tik iš raidžių, skaitmenų ir brūkšnelių.",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Ar tikrai norite ištrinti %s katalogus?",
    "AssetTableField.REALLYDELETE": "Ar tikrai norite ištrinti pažymėtas bylas?",
    "AssetTableField.MOVING": "Perkeliami %s failai(-as)",
    "CMSMAIN.AddSearchCriteria": "Pridėti",
    "WidgetAreaEditor.TOOMANY": "Atsiprašome, jūs pasiekėte valdinklių limitą šioje zonoje",
    "AssetAdmin.ConfirmDelete": "Ar tikrai norite ištrinti šį katalogą ir visas jame esančias bylas?",
    "Folder.Name": "Katalogo pavadinimas",
    "Tree.AddSubPage": "Pridėti naują puslapį čia",
    "Tree.Duplicate": "Kopijuoti",
    "Tree.EditPage": "Redaguoti",
    "Tree.ThisPageOnly": "Tik šį puslapį",
    "Tree.ThisPageAndSubpages": "Šį puslapį ir visus po juo",
    "Tree.ShowAsList": "Rodyti žemesnius pusl. kaip sąrašą",
    "CMSMain.ConfirmRestoreFromLive": "Ar tikrai norite kopijuoti publikuotą turinį į juodraštinę svetainę?",
    "CMSMain.RollbackToVersion": "Ar tikrai norite atstatyti šį puslapį į #%s versiją?",
    "URLSEGMENT.Edit": "Redaguoti",
    "URLSEGMENT.OK": "Gerai",
    "URLSEGMENT.Cancel": "Atšaukti"
});
}