// This file was generated by silverstripe/cow from javascript/lang/src/mi.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('mi', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Kei te tino hiahia muku i ngā kōpaki %s?",
    "AssetAdmin.ConfirmDelete": "Kei te tino hiahia muku i tēnei kōpaki me ngā kōnae i roto?",
    "AssetTableField.MOVING": "Neke ana i te %s kōnae",
    "AssetTableField.REALLYDELETE": "Kei te tino hiahia muku i ngā kōnae kua tohua?",
    "CMSMAIN.ALERTCLASSNAME": "Ka whakahōutia te momo whārangi i muri i te tiaki i te whārangi",
    "CMSMAIN.AddSearchCriteria": "Tāpiri Paearu",
    "CMSMAIN.CANTADDCHILDREN": "Kāore e taea te tāpiri tamariki ki te kōpuku kua tīpakotia",
    "CMSMAIN.DELETINGPAGES": "Muku whārangi ana...",
    "CMSMAIN.ERRORADDINGPAGE": "Hapa tāpiri whārangi",
    "CMSMAIN.ERRORDELETINGPAGES": "Kua hapa te muku whārangi",
    "CMSMAIN.ERRORFILTERPAGES": "Kāore i taea te tātari i te rākau kia whakaaturia ngā whārangi kua hurihia anake<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "Kua hapa te whakaputa whārangi",
    "CMSMAIN.ERRORREVERTING": "Kua hapa te hoki ki ngā ihirangi hohe",
    "CMSMAIN.ERRORUNFILTER": "Rākau tē tātaritia",
    "CMSMAIN.FILTEREDTREE": "Me whakaatu te rākau kua tātaritia i ngā whārangi kua hurihia anake",
    "CMSMAIN.PUBLISHING": "Whakaputa ana...",
    "CMSMAIN.PUBLISHINGPAGES": "Whakaputa whārangi ana...",
    "CMSMAIN.REALLYDELETEPAGES": "Kei te tino hiahia muku i ngā whārangi kua tohua %s?",
    "CMSMAIN.RESTORING": "Whakaora ana...",
    "CMSMAIN.SAVING": "Tiaki ana...",
    "CMSMAIN.SELECTMOREPAGES": "Kua kōwhiria e %s ngā whārangi.\n\nHe tika kia mahia tēnei mahi?",
    "CMSMAIN.SELECTONEPAGE": "Kōwhiria kotahi whārangi i te iti rawa.",
    "CMSMAIN.URLSEGMENTVALIDATION": "Ka taea anake ngā pūāhua, ngā mati me ngā tohuhono i ngā PRO.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Me tiaki i te whārangi i mua i te tāpiri tamariki ki raro",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "Kei te tino hiahia hoki ki te tauira #%s o tēnei whārangi?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "Ingoa kōpaki",
    "Tree.AddSubPage": "Tāpiri whārangi hou ki konei",
    "Tree.Duplicate": "Tārite",
    "Tree.EditPage": "Whakatika",
    "Tree.ShowAsList": "Whakaatu tamariki hei rārangi",
    "Tree.ThisPageAndSubpages": "Tēnei whārangi me ngā whārangi iti",
    "Tree.ThisPageOnly": "Tēnei whārangi anake",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "Whakakore",
    "URLSEGMENT.Edit": "Whakatika",
    "URLSEGMENT.OK": "ĀE",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "Aroha noa, kua taea te mōrahi o ngā taupānga iti i tēnei wāhi"
});
}