// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/nb.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('nb', {
    "CMSMAIN.ALERTCLASSNAME": "Sidetypen vil bare bli oppdatert når siden blir lagret",
    "CMSMain.RollbackToVersion": "Vil du virkelig rulle tilbake til versjon #%s av denne siden?",
    "CMSMAIN.CANTADDCHILDREN": "You can't add children to the selected node",
    "CMSMAIN.PUBLISHINGPAGES": "Publiserer sider ...",
    "CMSMAIN.SELECTMOREPAGES": "Du har valgt %s sider.\n\nVil du virkelig utføre denne handlingen?",
    "CMSMAIN.SAVING": "lagrer ...",
    "CMSMAIN.ERRORDELETINGPAGES": "Feil ved sletting av sider",
    "URLSEGMENT.Edit": "Rediger",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Du må lagre siden før du kan legge til undersider.",
    "CMSMAIN.PUBLISHING": "Publiserer ...",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs can only be made up of letters, digits and hyphens.",
    "URLSEGMENT.Cancel": "Avbryt",
    "Tree.ShowAsList": "Vis undersider som en liste",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "Tree.ThisPageOnly": "Bare denne siden",
    "CMSMain.ConfirmRestoreFromLive": "Vil du virkelig kopiere den publiserte siden til utkastsiden?",
    "CMSMAIN.ERRORPUBLISHING": "Feil ved publisering av sider",
    "CMSMAIN.ERRORADDINGPAGE": "Feil ved opprettelse av side",
    "AssetTableField.REALLYDELETE": "Vil du virkelig slette de merkede filene?",
    "CMSMAIN.RESTORING": "Gjenoppretter ...",
    "AssetTableField.MOVING": "Flytter %s file(r)",
    "Tree.EditPage": "Rediger",
    "URLSEGMENT.OK": "OK",
    "CMSMAIN.ERRORUNFILTER": "Unfiltered tree",
    "CMSMAIN.FILTEREDTREE": "Filtered tree to only show changed pages",
    "AssetAdmin.ConfirmDelete": "Vil du virkelig slette denne mappen og alle filer som ligger i den?",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Vil du virkelig slette %s mapper?",
    "CMSMAIN.AddSearchCriteria": "Legg til kriterie",
    "Tree.Duplicate": "Dupliser",
    "Tree.ThisPageAndSubpages": "Denne siden og undersider",
    "WidgetAreaEditor.TOOMANY": "Beklager, du har for mange \"widgets\" i dette området",
    "CMSMAIN.DELETINGPAGES": "Sletter sider ...",
    "Folder.Name": "Mappenavn",
    "CMSMAIN.REALLYDELETEPAGES": "Vil du virkelig slette de %s merkede sidene?",
    "CMSMAIN.SELECTONEPAGE": "Vennligst velg minst én side.",
    "Tree.AddSubPage": "Legg til ny side her",
    "CMSMAIN.ERRORFILTERPAGES": "Could not filter tree to only show changed pages<br />%s"
});
}