// This file was generated by silverstripe/cow from javascript/lang/src/nl.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Wil je echt %s mappen verwijderen?",
    "AssetAdmin.ConfirmDelete": "Wilt u deze map verwijderen, en alle bestanden er in?",
    "AssetTableField.MOVING": "Verplaats %s bestand(en)",
    "AssetTableField.REALLYDELETE": "Wilt u de geselecteerde bestanden verwijderen?",
    "CMSMAIN.ALERTCLASSNAME": "Het paginatype wordt aangepast na het opslaan van de pagina",
    "CMSMAIN.AddSearchCriteria": "Voeg criteria toe",
    "CMSMAIN.CANTADDCHILDREN": "U kan geen kinderen toevoegen aan de geselecteerde knoop",
    "CMSMAIN.DELETINGPAGES": "Pagina's verwijderen...",
    "CMSMAIN.ERRORADDINGPAGE": "Fout bij toevoegen van de pagina",
    "CMSMAIN.ERRORDELETINGPAGES": "Fout bij verwijderen van de pagina's",
    "CMSMAIN.ERRORFILTERPAGES": "Kon de paginastructuur niet filteren om alleen aangepaste pagina's te tonen.<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "Fout bij het publiceren van de pagina's",
    "CMSMAIN.ERRORREVERTING": "Fout bij het terugdraaien naar de gepubliceerde pagina",
    "CMSMAIN.ERRORUNFILTER": "Ongefilterde structuur",
    "CMSMAIN.FILTEREDTREE": "Gefilterd om alleen aangepaste pagina's te tonen",
    "CMSMAIN.PUBLISHING": "Publiceren...",
    "CMSMAIN.PUBLISHINGPAGES": "Pagina's aan het publiceren...",
    "CMSMAIN.REALLYDELETEPAGES": "Wilt u echt de %s geselecteerde pagina's verwijderen?",
    "CMSMAIN.RESTORING": "Herstellen...",
    "CMSMAIN.SAVING": "opslaan...",
    "CMSMAIN.SELECTMOREPAGES": "U hebt pagina(s) %s geselecteerd. \n\nWilt u deze actie uitvoeren?",
    "CMSMAIN.SELECTONEPAGE": "Selecteer minstens 1 pagina.",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs kunnen alleen bestaan uit letters, cijfers en koppeltekens.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "U moet de pagina opslaan voordat u onderliggende pagina's kan toevoegen",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "Wil je echt terugdraaien naar versie #%s van deze pagina?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "Mapnaam",
    "Tree.AddSubPage": "Voeg nieuwe pagina toe",
    "Tree.Duplicate": "Dupliceren",
    "Tree.EditPage": "Aanpassen",
    "Tree.ShowAsList": "Toon onderliggende pagina's als lijst",
    "Tree.ThisPageAndSubpages": "Deze pagina en subpagina's",
    "Tree.ThisPageOnly": "Enkel deze pagina",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "Annuleren",
    "URLSEGMENT.Edit": "Aanpassen",
    "URLSEGMENT.OK": "OK",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "Sorry, u hebt de maximaal aantal widgets bereikt in dit gebied"
});
}