// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/nl.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('nl', {
    "CMSMAIN.ALERTCLASSNAME": "Het paginatype wordt aangepast na opslaan van de pagina",
    "CMSMain.RollbackToVersion": "Do you really want to roll back to version #%s of this page?",
    "CMSMAIN.CANTADDCHILDREN": "Je kunt geen kinderen toevoegen aan de geselecteerde knoop",
    "CMSMAIN.PUBLISHINGPAGES": "Paginas aan het publiceren...",
    "CMSMAIN.SELECTMOREPAGES": "Je hebt pagina(s) %s geselecteerd. \n\nWil je deze actie uitvoeren?",
    "CMSMAIN.SAVING": "opslaan...",
    "CMSMAIN.ERRORDELETINGPAGES": "Fout bij verwijderen paginas",
    "URLSEGMENT.Edit": "Aanpassen",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "U moet de pagina opslaan voordat u kinderen kan toevoegen",
    "CMSMAIN.PUBLISHING": "Publiceren...",
    "CMSMAIN.URLSEGMENTVALIDATION": "URLs kunnen alleen bestaan uit letters, cijfers en koppeltekens.",
    "URLSEGMENT.Cancel": "Annuleren",
    "Tree.ShowAsList": "Toon kinderen als lijst",
    "CMSMAIN.ERRORREVERTING": "Error reverting to live content",
    "Tree.ThisPageOnly": "Enkel deze pagina",
    "CMSMain.ConfirmRestoreFromLive": "Do you really want to copy the published content to the draft site?",
    "CMSMAIN.ERRORPUBLISHING": "Verwijder gepubliceerde paginas",
    "CMSMAIN.ERRORADDINGPAGE": "Fout toevoegen pagina",
    "AssetTableField.REALLYDELETE": "Wil je de geselecteerde bestanden verwijderen?",
    "CMSMAIN.RESTORING": "Herstellen...",
    "AssetTableField.MOVING": "Verplaats %s bestand(en)",
    "Tree.EditPage": "Aanpassen",
    "URLSEGMENT.OK": "OK",
    "CMSMAIN.ERRORUNFILTER": "Ongefilterde structuur",
    "CMSMAIN.FILTEREDTREE": "Gefilterd om alleen aangepaste paginas te tonen",
    "AssetAdmin.ConfirmDelete": "Wil je deze map verwijderen en alle bestanden??",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Wil je deze mappen %s verwijderen?",
    "CMSMAIN.AddSearchCriteria": "Voeg criteria toe",
    "Tree.Duplicate": "Dupliceren",
    "Tree.ThisPageAndSubpages": "Deze pagina en subpagina's",
    "WidgetAreaEditor.TOOMANY": "Sorry, je hebt de maximaal aantal widgets bereikt",
    "CMSMAIN.DELETINGPAGES": "Paginas verwijderen...",
    "Folder.Name": "Mapnaam",
    "CMSMAIN.REALLYDELETEPAGES": "Wil je echt de geselecteerde %s pagina's verwijderen?",
    "CMSMAIN.SELECTONEPAGE": "Selecteer minstens 1 pagina.",
    "Tree.AddSubPage": "Voeg nieuwe pagina toe",
    "CMSMAIN.ERRORFILTERPAGES": "Kon niet filteren om alleen paginas <br />%s te tonen."
});
}