// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/pl.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('pl', {
    "CMSMAIN.ALERTCLASSNAME": "Ta strona zostanie zaktualizowana po jej zapisaniu",
    "CMSMain.RollbackToVersion": "Czy na pewno cofnąć do wersji #%s tej strony?",
    "CMSMAIN.CANTADDCHILDREN": "Nie można dodać stron podrzędnych",
    "CMSMAIN.PUBLISHINGPAGES": "Publikacja strony...",
    "CMSMAIN.SELECTMOREPAGES": "Zaznaczono %s stron.\n\nCzy na pewno chcesz wykonać tę akcje?",
    "CMSMAIN.SAVING": "Zapisywanie...",
    "CMSMAIN.ERRORDELETINGPAGES": "Błąd podczas usuwania stron",
    "URLSEGMENT.Edit": "Edytuj",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Należy najpierw zapisać stronę, aby móc dodać strony podrzędne",
    "CMSMAIN.PUBLISHING": "Publikacja...",
    "CMSMAIN.URLSEGMENTVALIDATION": "Adres URL może składać się tylko z liter, cyfr i łączników.",
    "URLSEGMENT.Cancel": "Anuluj",
    "Tree.ShowAsList": "Show children as list",
    "CMSMAIN.ERRORREVERTING": "Błąd podczas powrotu do opublikowanej strony",
    "Tree.ThisPageOnly": "This page only",
    "CMSMain.ConfirmRestoreFromLive": "Czy na pewno skopiować opublikowaną treść do strony roboczej?",
    "CMSMAIN.ERRORPUBLISHING": "Błąd podczas publikacji stron",
    "CMSMAIN.ERRORADDINGPAGE": "Błąd przy dodawaniu strony",
    "AssetTableField.REALLYDELETE": "Czy na pewno usunąć zaznaczone pliki??",
    "CMSMAIN.RESTORING": "Odzyskiwanie...",
    "AssetTableField.MOVING": "Przenoszenie %s plików",
    "Tree.EditPage": "Edytuj",
    "URLSEGMENT.OK": "OK",
    "CMSMAIN.ERRORUNFILTER": "Nie można było cofnąć filtrowania drzewa<br />%s",
    "CMSMAIN.FILTEREDTREE": "Drzewo filtrowane pokazujące tylko zmienione strony",
    "AssetAdmin.ConfirmDelete": "Czy na pewno usunąć ten folder i wszystkie pliki w nim zawarte?",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Czy na pewno usunąć %s folderów?",
    "CMSMAIN.AddSearchCriteria": "Dodaj kryteria",
    "Tree.Duplicate": "Duplicate",
    "Tree.ThisPageAndSubpages": "This page and subpages",
    "WidgetAreaEditor.TOOMANY": "Przepraszam, ale osiągnięto maksymalną ilość widgetów w tym obszarze",
    "CMSMAIN.DELETINGPAGES": "Usuwanie stron...",
    "Folder.Name": "Nazwa folderu",
    "CMSMAIN.REALLYDELETEPAGES": "Czy na pewno zaznaczone strony %s usunąć?",
    "CMSMAIN.SELECTONEPAGE": "Proszę wybrać przynajmniej jedną stronę",
    "Tree.AddSubPage": "Dodaj tutaj nową stronę",
    "CMSMAIN.ERRORFILTERPAGES": "Nie można było filtrować drzewa<br />%s"
});
}