// This file was generated by silverstripe/cow from javascript/lang/src/ru.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Вы действительно хотите удалить директории (%s шт.)?",
    "AssetAdmin.ConfirmDelete": "Вы действительно хотите удалить эту директорию и все файлы в ней?",
    "AssetTableField.MOVING": "Перемещение  файлов (%s шт.)",
    "AssetTableField.REALLYDELETE": "Вы действительно хотите удалить отмеченные файлы?",
    "CMSMAIN.ALERTCLASSNAME": "Тип страницы будет изменён после её сохранения.",
    "CMSMAIN.AddSearchCriteria": "Добавить условие",
    "CMSMAIN.CANTADDCHILDREN": "Невозможно добавить вложенную страницу для этой страницы",
    "CMSMAIN.DELETINGPAGES": "Удаление страниц...",
    "CMSMAIN.ERRORADDINGPAGE": "Ошибка при добавлении страницы",
    "CMSMAIN.ERRORDELETINGPAGES": "Ошибка при удалении страниц",
    "CMSMAIN.ERRORFILTERPAGES": "Невозможно отфильтровать дерево для отображения только изменённых страниц<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "Ошибка при публикации страниц",
    "CMSMAIN.ERRORREVERTING": "Ошибка при получении содержимого",
    "CMSMAIN.ERRORUNFILTER": "Неотфильтрованное дерево",
    "CMSMAIN.FILTEREDTREE": "Отфильтрованное дерево изменённых страниц",
    "CMSMAIN.PUBLISHING": "Публикация...",
    "CMSMAIN.PUBLISHINGPAGES": "Публикация страниц...",
    "CMSMAIN.REALLYDELETEPAGES": "Вы действительно хотите удалить выбранные страницы (%s шт.)?",
    "CMSMAIN.RESTORING": "Восстановление...",
    "CMSMAIN.SAVING": "сохранение...",
    "CMSMAIN.SELECTMOREPAGES": "Выбрано страниц: %s.\n\nВы действительно хотите выполнить выбранное действие?",
    "CMSMAIN.SELECTONEPAGE": "Пожалуйста, выберите хотя бы одну страницу.",
    "CMSMAIN.URLSEGMENTVALIDATION": "Адрес может состоять только из букв, цифр и дефисов.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Необходимо сохранить страницу, прежде чем добавлять вложенные страницы",
    "CMSMain.Archive": "Вы действительно хотите отправить в архив эту страницу и все вложенные страницы?\n\nЭта страница и все вложенные страницы будут сняты с публикации и отправлены в архив.",
    "CMSMain.ConfirmRestoreFromLive": "Вы действительно хотите вернуть страницу к состоянию опубликованной версии?",
    "CMSMain.DeleteFromDraft": "Вы уверены что хотите удалить страницу с чернового сайта?\n\nСтраница останется на опубликованном сайте.",
    "CMSMain.Restore": "Вы действительно хотите восстановить эту страницу из архива?",
    "CMSMain.RestoreToRoot": "Вы уверены что хотите восстановить данную страницу из архива?\n\nПоскольку родительская страница недоступна данная страница будет восстановлена в корень сайта.",
    "CMSMain.RollbackToVersion": "Вы действительно хотите восстановить версию #%s этой страницы?",
    "CMSMain.Unpublish": "Вы уверены что хотите удалить страницу с опубликованного сайта?\n\nСтраница останется в черновиках.",
    "Folder.Name": "Имя директории",
    "Tree.AddSubPage": "Добавить новую страницу",
    "Tree.Duplicate": "Создать копию",
    "Tree.EditPage": "Редактировать",
    "Tree.ShowAsList": "Показать страницы в виде списка",
    "Tree.ThisPageAndSubpages": "Вместе с вложенными страницами",
    "Tree.ThisPageOnly": "Только этой страницы",
    "Tree.ViewPage": "Просмотр",
    "URLSEGMENT.Cancel": "Отмена",
    "URLSEGMENT.Edit": "Изменить",
    "URLSEGMENT.OK": "ОК",
    "URLSEGMENT.UpdateURL": "Обновить Адрес",
    "WidgetAreaEditor.TOOMANY": "Достигнуто максимальное число виджетов в этом разделе."
});
}