// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ru.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ru', {
    "CMSMAIN.ALERTCLASSNAME": "Тип страницы будет изменён после её сохранения.",
    "CMSMain.RollbackToVersion": "Вы действительно хотите восстановить версию #%s этой страницы?",
    "CMSMAIN.CANTADDCHILDREN": "Невозможно добавить вложенную страницу для этой страницы",
    "CMSMAIN.PUBLISHINGPAGES": "Публикация страниц...",
    "CMSMAIN.SELECTMOREPAGES": "Выбрано страниц: %s.\n\nВы действительно хотите выполнить выбранное действие?",
    "CMSMAIN.SAVING": "сохранение...",
    "CMSMAIN.ERRORDELETINGPAGES": "Ошибка при удалении страниц",
    "URLSEGMENT.Edit": "Изменить",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Необходимо сохранить страницу, прежде чем добавлять вложенные страницы",
    "CMSMAIN.PUBLISHING": "Публикация...",
    "CMSMAIN.URLSEGMENTVALIDATION": "Адрес может состоять только из букв, цифр и дефисов.",
    "URLSEGMENT.Cancel": "Отмена",
    "Tree.ShowAsList": "Показать страницы в виде списка",
    "CMSMAIN.ERRORREVERTING": "Ошибка при получении содержимого",
    "Tree.ThisPageOnly": "Только этой страницы",
    "CMSMain.ConfirmRestoreFromLive": "Вы действительно хотите скопировать опубликованное содержимое на черновой сайт?",
    "CMSMAIN.ERRORPUBLISHING": "Ошибка при публикации страниц",
    "CMSMAIN.ERRORADDINGPAGE": "Ошибка при добавлении страницы",
    "AssetTableField.REALLYDELETE": "Вы действительно хотите удалить отмеченные файлы?",
    "CMSMAIN.RESTORING": "Восстановление...",
    "AssetTableField.MOVING": "Перемещение  файлов (%s шт.)",
    "Tree.EditPage": "Редактировать",
    "URLSEGMENT.OK": "ОК",
    "CMSMAIN.ERRORUNFILTER": "Неотфильтрованное дерево",
    "CMSMAIN.FILTEREDTREE": "Отфильтрованное дерево изменённых страниц",
    "AssetAdmin.ConfirmDelete": "Вы действительно хотите удалить эту директорию и все файлы в ней?",
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Вы действительно хотите удалить директории (%s шт.)?",
    "CMSMAIN.AddSearchCriteria": "Добавить условие",
    "Tree.Duplicate": "Создать копию",
    "Tree.ThisPageAndSubpages": "Вместе с вложенными страницами",
    "WidgetAreaEditor.TOOMANY": "Достигнуто максимальное число виджетов в этом разделе.",
    "CMSMAIN.DELETINGPAGES": "Удаление страниц...",
    "Folder.Name": "Имя директории",
    "CMSMAIN.REALLYDELETEPAGES": "Вы действительно хотите удалить выбранные страницы (%s шт.)?",
    "CMSMAIN.SELECTONEPAGE": "Пожалуйста, выберите хотя бы одну страницу.",
    "Tree.AddSubPage": "Добавить новую страницу",
    "CMSMAIN.ERRORFILTERPAGES": "Невозможно отфильтровать дерево для отображения только изменённых страниц<br />%s"
});
}