// This file was generated by silverstripe/cow from javascript/lang/src/ru.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "Вы действительно хотите удалить директории (%s шт.)?",
    "AssetAdmin.ConfirmDelete": "Вы действительно хотите удалить эту директорию и все файлы в ней?",
    "AssetTableField.MOVING": "Перемещение  файлов (%s шт.)",
    "AssetTableField.REALLYDELETE": "Вы действительно хотите удалить отмеченные файлы?",
    "CMSMAIN.ALERTCLASSNAME": "Тип страницы будет изменён после её сохранения.",
    "CMSMAIN.AddSearchCriteria": "Добавить условие",
    "CMSMAIN.CANTADDCHILDREN": "Невозможно добавить вложенную страницу для этой страницы",
    "CMSMAIN.DELETINGPAGES": "Удаление страниц...",
    "CMSMAIN.ERRORADDINGPAGE": "Ошибка при добавлении страницы",
    "CMSMAIN.ERRORDELETINGPAGES": "Ошибка при удалении страниц",
    "CMSMAIN.ERRORFILTERPAGES": "Невозможно отфильтровать дерево для отображения только изменённых страниц<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "Ошибка при публикации страниц",
    "CMSMAIN.ERRORREVERTING": "Ошибка при получении содержимого",
    "CMSMAIN.ERRORUNFILTER": "Неотфильтрованное дерево",
    "CMSMAIN.FILTEREDTREE": "Отфильтрованное дерево изменённых страниц",
    "CMSMAIN.PUBLISHING": "Публикация...",
    "CMSMAIN.PUBLISHINGPAGES": "Публикация страниц...",
    "CMSMAIN.REALLYDELETEPAGES": "Вы действительно хотите удалить выбранные страницы (%s шт.)?",
    "CMSMAIN.RESTORING": "Восстановление...",
    "CMSMAIN.SAVING": "сохранение...",
    "CMSMAIN.SELECTMOREPAGES": "Выбрано страниц: %s.\n\nВы действительно хотите выполнить выбранное действие?",
    "CMSMAIN.SELECTONEPAGE": "Пожалуйста, выберите хотя бы одну страницу.",
    "CMSMAIN.URLSEGMENTVALIDATION": "Адрес может состоять только из букв, цифр и дефисов.",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "Необходимо сохранить страницу, прежде чем добавлять вложенные страницы",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "Вы действительно хотите восстановить версию #%s этой страницы?",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "Имя директории",
    "Tree.AddSubPage": "Добавить новую страницу",
    "Tree.Duplicate": "Создать копию",
    "Tree.EditPage": "Редактировать",
    "Tree.ShowAsList": "Показать страницы в виде списка",
    "Tree.ThisPageAndSubpages": "Вместе с вложенными страницами",
    "Tree.ThisPageOnly": "Только этой страницы",
    "URLSEGMENT.Cancel": "Отмена",
    "URLSEGMENT.Edit": "Изменить",
    "URLSEGMENT.OK": "ОК",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "Достигнуто максимальное число виджетов в этом разделе."
});
}