// This file was generated by silverstripe/cow from javascript/lang/src/zh.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('zh', {
    "AssetAdmin.BATCHACTIONSDELETECONFIRM": "是否确定删除 %s 个文件夹？",
    "AssetAdmin.ConfirmDelete": "是否确定删除该文件夹以及所有包含的文件？",
    "AssetTableField.MOVING": "正在移动 %s 文件",
    "AssetTableField.REALLYDELETE": "是否确定删除标记的文件？",
    "CMSMAIN.ALERTCLASSNAME": "将在页面保存后上传页面类型",
    "CMSMAIN.AddSearchCriteria": "添加标准",
    "CMSMAIN.CANTADDCHILDREN": "您无法将儿童添加至所选节点",
    "CMSMAIN.DELETINGPAGES": "正在删除页面...",
    "CMSMAIN.ERRORADDINGPAGE": "错误添加页面",
    "CMSMAIN.ERRORDELETINGPAGES": "删除页面时出错",
    "CMSMAIN.ERRORFILTERPAGES": "无法过滤树形结构，以便仅显示已更改页面<br />%s",
    "CMSMAIN.ERRORPUBLISHING": "错误发布页面",
    "CMSMAIN.ERRORREVERTING": "返回至实时内容的错误",
    "CMSMAIN.ERRORUNFILTER": "未经过滤的树形结构",
    "CMSMAIN.FILTEREDTREE": "已对树形结构进行过滤，进而可以仅显示更改过的页面",
    "CMSMAIN.PUBLISHING": "正在发布...",
    "CMSMAIN.PUBLISHINGPAGES": "正在发布页面...",
    "CMSMAIN.REALLYDELETEPAGES": "是否确定删除 %s 标记的页面？",
    "CMSMAIN.RESTORING": "正在恢复...",
    "CMSMAIN.SAVING": "正在保存...",
    "CMSMAIN.SELECTMOREPAGES": "您选择了 %s 个页面。\n\n是否确定执行该操作？",
    "CMSMAIN.SELECTONEPAGE": "请至少选择 1 个页面。",
    "CMSMAIN.URLSEGMENTVALIDATION": "URL 仅能由字母、数字和连字符组成。",
    "CMSMAIN.WARNINGSAVEPAGESBEFOREADDING": "将儿童添加在下面之前，您必须保存一个页面",
    "CMSMain.Archive": "Are you sure you want to archive this page and all of its children pages?\n\nThis page and all of its children will be unpublished and sent to the archive.",
    "CMSMain.ConfirmRestoreFromLive": "Are you sure you want to revert draft to when the page was last published?",
    "CMSMain.DeleteFromDraft": "Are you sure you want to remove your page from the draft site?\n\nThis page will remain on the published site.",
    "CMSMain.Restore": "Are you sure you want to restore this page from archive?",
    "CMSMain.RestoreToRoot": "Are you sure you want to restore this page from archive?\n\nBecause the parent page is not available this will be restored to the top level.",
    "CMSMain.RollbackToVersion": "是否确定回滚至该页面的第 #%s 版？",
    "CMSMain.Unpublish": "Are you sure you want to remove your page from the published site?\n\nThis page will still be available in the sitetree as draft.",
    "Folder.Name": "文件夹名称",
    "Tree.AddSubPage": "在此添加新页面",
    "Tree.Duplicate": "复制",
    "Tree.EditPage": "编辑",
    "Tree.ShowAsList": "将儿童显示为列表",
    "Tree.ThisPageAndSubpages": "本页和子页面",
    "Tree.ThisPageOnly": "仅该页",
    "Tree.ViewPage": "View",
    "URLSEGMENT.Cancel": "取消",
    "URLSEGMENT.Edit": "编辑",
    "URLSEGMENT.OK": "确定",
    "URLSEGMENT.UpdateURL": "Update URL",
    "WidgetAreaEditor.TOOMANY": "对不起，该区域的小工具数量已经达到最大数量"
});
}