---
Name: cmsextensions
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\CMS\Model\SiteTreeFileExtension
---
Name: cmsmodals
---
SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\CMS\Forms\InternalLinkModalExtension
---
Name: cmscampaigns
Only:
  moduleexists: 'silverstripe/campaign-admin'
---
SilverStripe\CampaignAdmin\CampaignAdmin:
  placeholder_group_classes:
    - 'SilverStripe\CMS\Model\SiteTree'
