#!/bin/sh

### USAGE: before_script <base-folder> <travis-branch>

BUILD_DIR=$1

# Environment info
echo "# Environment info"
echo " - `php --version`"
echo " - `mysql --version`"
echo " - `pg_config --version`"
echo " - SQLite3 `sqlite3 -version`"
echo ""

# Fetch all dependencies
# TODO Replace with different composer.json variations

echo "Checking out installer@$TRAVIS_BRANCH"
git clone --depth=100 --quiet -b $TRAVIS_BRANCH git://github.com/silverstripe/silverstripe-installer.git $BUILD_DIR

echo "Checking out sqlite3@master"
git clone --depth=100 --quiet git://github.com/silverstripe-labs/silverstripe-sqlite3.git $BUILD_DIR/sqlite3

echo "Checking out postgresql@master"
git clone --depth=100 --quiet git://github.com/silverstripe/silverstripe-postgresql.git $BUILD_DIR/postgresql

echo "Checking out sapphire@$TRAVIS_BRANCH"
git clone --depth=100 --quiet -b $TRAVIS_BRANCH git://github.com/silverstripe/sapphire.git $BUILD_DIR/framework

# Copy setup files
cp $BUILD_DIR/framework/tests/travis/_ss_environment.php $BUILD_DIR
cp $BUILD_DIR/framework/tests/travis/_config.php $BUILD_DIR/mysite

# Copy actual project code into build directory (checked out by travis)
cp -r . $BUILD_DIR/cms

cd $BUILD_DIR
